### ISSUE TITLE
[GL Renderer] BIOS screen glitches

### ISSUE THREAD

**Issue by rz5** [libretro/beetle-psx-libretro#246] opened 2017-10-17 03:45 UTC
Shortly after the Sony Computer Entertainment text appears, the text will disappear along with one of the logo's inner triangles and the jingle will be stuck in a loop, all of this in a span of 4 seconds.

The software and vulkan renderers do not have this bug. Is it perhaps a timing glitch? Maybe the value the GL renderer is using for the video clock doesn't match up with what the actual core uses?

![](https://i.snag.gy/hxTuG1.jpg)

**Comment by simias** [comment] 2017-10-17 13:16
Yeah I've noticed that a while ago, it's a good test case actually since the number of polygons in this screen is extremely low (2 triangles and two quads IIRC) so it shouldn't be too hard to figure out what's going on. My guess would be that the screen is refreshed at the bad moment, so we display the image before the 2nd triangle is drawn. IIRC not all BIOS versions have this issue.

An other thing to keep in mind is that the BIOS uses a rather uncommon framebuffer configuration, instead of double-buffering it uses a single "full screen" 640x480 framebuffer. This is uncommon because it eats up more than half (~59%) of all VRAM and reduces the space available for textures drastically. Of course the scene in the BIOS is so simplistic that it's not a problem in practice:

![bios-vram](https://user-images.githubusercontent.com/7925386/31666753-a0d4893a-b34d-11e7-88ee-5c1a2875bd46.png)

But the lack of double-buffering might be the problem for the GL renderer, it means that the display timing is crucial, too early or too late and it'll mess up.

That being said if that's the case I don't understand why Vulkan doesn't have the same issue, does it use different timings?

**Comment by rz5** [comment] 2017-10-17 15:07
In an attempt to fix this, I ensured that all renderers to roughly report the same geometry and timing info to the frontend.

So the sample rate is SOUND FREQUENCY and framerate will be FPS_PAL or FPS_NTSC. The fix didn't work.

**Comment by saftle** [comment] 2017-10-18 20:18
This is a duplicate of https://github.com/libretro/beetle-psx-libretro/issues/43#issuecomment-223122986.

**Comment by Papermanzero** [comment] 2018-06-24 20:08
This issue is still valid for the OpenGL renderer. Verfied it also some minutes ago.

**Comment by Papermanzero** [comment] 2018-06-25 13:11
Maybe interessting to know. The texture filtering is not applied during the boot screen.
The text appears at the very end of the booting sequence.
![dino crisis 2-180625-143320](https://user-images.githubusercontent.com/10263536/41851948-eec1aae0-7889-11e8-81cd-38ebc9795c1b.png)

**Comment by saftle** [comment] 2018-07-26 15:58
This problem no longer seems to exist. Just tested with 581a08fc62a21515e4f9d9fb2d0e96e5da434f43

**Comment by Papermanzero** [comment] 2018-07-26 21:20
I still can reproduce the issue

**Comment by saftle** [comment] 2018-07-27 06:01
Oh, I didn't mean that the commit itself fixed the issue, but as of the latest commit, the problem as shown in the first screenshot, is no longer the case on my end.

**Comment by Papermanzero** [comment] 2018-07-27 06:57
That is interessting. Because i still have the issue. First everything looks ok. Then the text disappears.

**Comment by RepeatingDigits** [comment] 2018-12-19 01:50
I'm experiencing this, but with the Vulkan renderer. It's really not consistent, but Bugs Bunny Time Busters is a great game to test this issue.

**Closed** 2019-10-28 02:18 UTC
