### ISSUE TITLE
[Vulkan/OpenGL] Colony Wars Red Sun (USA) [SCUS-00866] incorrect placement of intro video.

### ISSUE THREAD

**Issue by ofry** [libretro/beetle-psx-libretro#162] opened 2017-02-25 04:49 UTC
The intro video is stuck to the bottom of the screen.

Expected behavior:
Video should be centered vertically.

There is screenshots:

![colony wars - red sun usa -170225-073644](https://cloud.githubusercontent.com/assets/11790863/23328298/f9a1f99e-fb2e-11e6-87f8-09363a7bdf60.png)
![colony wars - red sun usa -170225-073811](https://cloud.githubusercontent.com/assets/11790863/23328297/f9a0e310-fb2e-11e6-9584-705654c32fe9.png)

**Comment by ofry** [comment] 2017-02-25 04:51
Core version: Mednafen PSX HW 0.9.39.2 2613b5f

**Comment by Silanda** [comment] 2017-05-15 19:22
I get this problem with some games too, e.g. the PAL versions of Wipeout 2097 and Wip3out. Also, Ghost in the Shell's (NTSC-U) intro video is stretched to 4:3 ratio when it's supposed to be a widescreen aspect, although I'm not sure if the problem's related.

These problems do not occur for me on the SW core.

**Comment by twinaphex** [comment] 2018-07-18 09:06
Seems to be similar to this issue - 

https://github.com/libretro/beetle-psx-libretro/issues/346

**Comment by ggdrt** [comment] 2019-11-02 02:59
@twinaphex I took a look at this and it's not a bug with the renderers, it's a programming "error" in the game itself. The game is setting the GPU to output framebuffers that contain those black bars. It's accurate emulation unfortunately. I think this issue can be closed.

**Comment by ggdrt** [comment] 2019-11-05 01:54
Unlabeling and closing this since it's an issue with the game itself, not with any of the renderers.

**Closed by ggdrt** 2019-11-05 01:54 UTC
Labels: graphics bug - fmv offset, graphics bugs, opengl, vulkan
