### ISSUE TITLE
Lots of graphical issues with MGS1 (HW)

### ISSUE THREAD

**Issue by TomMultisensory** [libretro/beetle-psx-libretro#433] opened 2018-09-28 05:43 UTC
https://imgur.com/a/r7tyqwx

So this issue only happens in the HW Bettle core, and not the SW one. Basically, the graphics are messed up, and some thing appear misplaced. The water and cutscenes are also jacked up and the items are not displayed, but I don't have a screenshot of those.

**Comment by rz5** [comment] 2018-09-28 05:51
Use the vulkan renderer instead.
This is a duplicate of #381. Also see #414.

**Closed by rz5** 2018-09-28 05:51 UTC
Labels: duplicate
