### ISSUE TITLE
graphical issues that are not present in standalone mednafen

### ISSUE THREAD

**Issue by personaone** [libretro/beetle-psx-libretro#39] opened 2016-05-15 17:39 UTC
Hi Guys,

Just noticed the issue in FF8 - at the left edge of the bridge in Dollet, when characters pass a certain point they start blinking (flashing) rapidly. This isn't happening in Mednafen 0.9.38.7. Not sure if the Libretro core is behind on the source? The newest one shows that it's 0.9.38.6. Using the latest nighty RA as well with no special settings in the core menu.

**Comment by twinaphex** [comment] 2016-05-15 17:42
It might miss some insignificant things here and there. It can probably be backported easily.

Anyway, at this point, Beetle PSX is far ahead of 'standalone' so it's a fair tradeoff, I am fine with backporting whatever is needed to make things more accurate but first it needs to be found what has to be backported, and I don't want it to bump up compiler requirements, otherwise it needs to be rewritten.

**Comment by personaone** [comment] 2016-05-15 18:12
Right, thanks - i'm running all native, no upscaling or anything, haven't changed anything in the core settings :) Even tried turning off shaders and stuff, still the same thing. Interesting issue since it's been occuring ever since I remember. Just failed to report it then. Let me know if there's anything else I can test!

**Comment by Warriors-Blade** [comment] 2016-05-30 03:35
I can vouch for this issue, I have encountered it through various parts of the game and just to make sure I tested it with the latest vanilla and the issue is fixed.

Do you need a video sample showcasing the graphical glitch?

**Comment by twinaphex** [comment] 2016-05-30 03:39
We should first figure out which part was responsible for fixing this and then backport that.

**Comment by hizzlekizzle** [comment] 2016-05-30 03:47
Has anyone verified that standalone v0.9.38.6 had the same behavior? That is, is this actually something that can be resolved by backporting a fix, or was it divergent behavior from the start?

**Comment by Oggom** [comment] 2016-05-30 12:53
It's probably this change:

December 5, 2014:
	PSX: Fixed some precision-related bugs in the triangle rendering code; fixes the flickering-characters issue that occurs at several locations in "Final Fantasy 8".  Unfortunately, this fix does increase CPU usage a bit more that I would like, and it's going to be tricky to optimize the difference
	away.

**Comment by simias** [comment] 2016-06-09 18:31
@personaone you could try diff'ing the version of mednafen that fixed it with the one before that and see what changed in the GPU code (in `src/psx/gpu*`). At least that's where I'd start, hoping that there haven't been too many changes.

If you do this and the diff ends up being too big or too cryptic don't hesitate to paste it somewhere online, I'll have a look at it.

**Comment by personaone** [comment] 2016-06-09 18:40
Yeah I found the source for the version that introduced that change, but the previous to that, 0.9.36.5 - was hosted on Sourceforge and all of mednafen's file are gone from there o_O I wonder where I can find that thing now.

**Comment by Oggom** [comment] 2016-06-09 18:42
https://github.com/libretro/mednafen-git/commits/master

**Comment by personaone** [comment] 2016-06-09 20:17
@Oggom thanks for that

Here goes... a diff for the gpu.cpp is here:

http://pastebin.com/JVc1dvB6

And gpu.h:

http://pastebin.com/T09qrBZG

Let me know if this even makes sense :p

**Comment by simias** [comment] 2016-06-09 20:23
Can I get a savestate that exhibits this issue in FFVIII?

**Comment by personaone** [comment] 2016-06-09 20:35
Yep, sure.
[ff8.state3.zip](https://github.com/libretro/beetle-psx-libretro/files/307862/ff8.state3.zip)

**Comment by personaone** [comment] 2016-06-26 17:35
@simias any chance you could figure this one out? Let me know if I can help test anything furhter.

**Comment by mjuzikfrik** [comment] 2017-04-11 06:42
Any chance to fix this issue?

**Comment by NelsonRosenberg** [comment] 2017-07-11 06:15
Also would like to know if there is a fix available. Thank you.

**Comment by simias** [comment] 2017-10-04 20:44
I've managed to fix the flickering by porting some of the newer mednafen code, however I seem to have broken something else because now some polygons seem to randomly glitch out. My code is here if somebody wants to play with it: https://github.com/simias/beetle-psx-libretro/tree/gpu-precision

Also note that increasing the internal resolution is also broken, but that I know how to fix.

I'm going to keep trying but this GPU code has been so viciously butchered by our various hacks (increased IR, PGXP...) that it's a bit painful to merge back with upstream mednafen. If I can't figure this out I'm just going to import the current mednafen version as-is and then reimplement our hacks on top of it.

**Comment by simias** [comment] 2017-10-04 21:24
Okay, it was easier than I expected, I think the latest commit in my gpu-precision branch should've fixed it.

I haven't thoroughly tested it though, I'd appreciate it if somebody could give it a try and make sure that the issue is fixed *and* than I haven't introduced any regression.

If it works as intended I'll remove the C++11 code and fix the internal resolution hack and we should be good to go.

Slow and steady.

**Comment by twinaphex** [comment] 2017-10-05 01:29
I tested it, couldn't notice any regressions so it appears things are good.

The only thing I did notice in Dead or Alive 1 and wipeout XL was that there is sometimes some unintended geometry being drawn at the right hand side of the screen. This is only if 'memory only ' PGXP and perspective correction is enabled though, so maybe it's just the imperfect nature of those graphics features.

**Comment by simias** [comment] 2017-10-05 08:00
Cool, thank you for testing that!

**Comment by mjuzikfrik** [comment] 2017-10-05 09:17
Better late than never. Very good news! :)

**Comment by personaone** [comment] 2017-10-05 09:22
Wow it’s happening!:)

**Comment by simias** [comment] 2017-10-05 21:24
I've managed to get upscaling to work again *mostly*, however I have a weird seam in the textures that needs further debugging (probably a rounding error somewhere):

![ctr - crash team racing usa -171005-232226](https://user-images.githubusercontent.com/7925386/31253226-50c4d45e-aa24-11e7-9ee4-8a8f55d1fb48.png)

Anyway, progress!

**Comment by simias** [comment] 2017-10-06 09:18
I *think* it works now (needs more testing though). Note that the flickering glitch in FFVIII reappears when I increase the internal resolution, looks like this particular game is *very* finicky with its triangle drawing code. At least now it seems to work accurately at 1x so we're on a par with upstream.

**Comment by simias** [comment] 2017-10-06 19:08
Arg, I've just noted that 4x and up is broken, missing polygons everywhere. I doubt many people use that given the performance but still...

**Comment by personaone** [comment] 2017-10-06 19:12
I’ll take accuracy over res anyway;) awesome work!

**Closed** 2017-10-07 23:09 UTC

**Comment by simias** [comment] 2017-10-07 23:12
Okay, I fixed the issue at 4+x and tested it with a bunch of games, it seems to work fine as far as I can tell.

Also the flickering in FFVIII is now fixed even with increased IR so that's nice.

Please do report any regression I missed!
