### ISSUE TITLE
Silent hill glitches with pgxp

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#303] opened 2018-02-13 21:54 UTC
Start silent hill. The whole ground is glitching. 
Black rectangles all over the ground if pgxp mode with perspective correct texturing is activated.

**Comment by Papermanzero** [comment] 2018-02-17 22:26
Please find below a screenshot. You have to activate vulkan, pgxp, and perpective correct texturing
![silent hill-180217-232350](https://user-images.githubusercontent.com/10263536/36346165-d7de6944-1439-11e8-88d7-2f6495927bba.png)

**Comment by saftle** [comment] 2018-03-03 07:30
This is most likely a duplicate of https://github.com/libretro/beetle-psx-libretro/issues/257

**Comment by Papermanzero** [comment] 2018-03-03 09:10
Not sure. If i use pcsx-pgxp (standalone emulator) the game is working flawlessly with pgxp.

**Comment by saftle** [comment] 2018-03-03 09:52
@Papermanzero comparing it to PCSX-Reloaded sadly won't help. Since it's most likely #257, please try and change the renderer and retroarch's driver to GL rather than Vulkan. The bug was recently fixed in the GL renderer, but has not been fixed yet in Vulkan.

**Comment by saftle** [comment] 2018-03-04 07:27
I can confirm that https://github.com/libretro/beetle-psx-libretro/pull/312 fixed this issue and #257. Thank you so much @iCatButler.

**Closed** 2018-03-04 14:33 UTC
