### ISSUE TITLE
[Vulkan] Xenogears corrupt textures at 16x Internal Resolution

### ISSUE THREAD

**Issue by WhiteZeroX** [libretro/beetle-psx-libretro#476] opened 2019-01-05 16:16 UTC
## Description

Texture corruption on Vulkan renderer at 16x Internal Resolution. GL works normally at 16x. And Vulkan works fine at 8x and lower.
Interestingly, after changing the Internal Resolution, the texture corruption won't take affect until you move your character one step, or rotate the camera more than 1 degree (you can rotate it back and forth one degree in the same direction and the textures remain normal).

Normal at 8x: 
![](https://i.imgur.com/TuUZoTr.png)

Corrupt at 16x: 
![](https://i.imgur.com/HifhwOh.png)

(Not shown is that some character sprites also break apart)

### Version/Commit

- RetroArch: 1.7.5
- Beetle PSX HW: 0.9.44.1 1d6ba98

### Core options
- Internal GPU Resolution - 16x
- MDEC Chroma Filter - On
- Internal Color Depth - 32bpp
- Dither Pattern - Off

### Environment information

- OS: Windows 10 1809
- GPU: GeForce GTX 1070 - Driver 416.16

**Comment by Oschowa** [comment] 2019-01-12 01:00
I noticed a very similar thing when playing vagrant story, textures, especially the speech bubbles but also characters, start showing a currupt pattern. This does not happen instantly, but seems to be triggered by new speech bubbles appearing. Droping the internal res to 8x seems to work around it. I tested on linux with latest radv-git and amdvlk, so it's probably no dirver issue.

file:///home/oschowa/.config/retroarch/screenshots/vagrant_story_jp-190112-015120.png

file:///home/oschowa/.config/retroarch/screenshots/vagrant_story_jp-190112-015829.png

**Comment by SpiffyJUNIOR** [comment] 2019-03-14 19:53
This happens on Blasto too.
Windows 10 x64
i5-7300HQ
1050 Ti Mobile
Vulkan with latest drivers.

**Comment by brianblakely** [comment] 2019-04-08 00:53
Also experiencing this.

**Comment by brianblakely** [comment] 2019-05-07 15:18
I've noticed the texture corruption doesn't happen for me at 2x or 1x.

4x and higher manifest the issue. No other core option appears to affect this.

**Comment by saftle** [comment] 2019-05-11 07:58
Are you guys using any shaders? Noticed a similar issue at 16x resolution only when in combination with a specific shader.

**Comment by brianblakely** [comment] 2019-05-11 16:11
@saftle not me

**Comment by SpiffyJUNIOR** [comment] 2019-05-14 03:57
@saftle Tested both OpenGL and Vulkan, OpenGL is fine but shits the performance bed when bumped up to 16x (from full speed at 8x to 1-2FPS in 16x) Vulkan runs faster but runs into this issue too in several games. Also, no, not using any shaders.

**Comment by Sanaki** [comment] 2019-12-18 02:04
Tested against Vagrant Story (I can't reproduce the issue in Xenogears on Linux myself), I can confirm that commit 15765375c9d3065d0ab8a7bbe04bda355504f996 didn't have the issue at 16x, while the current definitely does. Unfortunately I can't do a proper bisect because I can't build a pretty massive chunk of the commits on Linux, but if someone else wants to give it a go, you might be able to locate the exact commit where it started.

**Comment by rz5** [comment] 2019-12-18 10:45
I just got done doing a git bisect.
The test case was that loading a Vagrant Story savestate, right before texture corruption happens on 16x upscale (for me), specifically when the Guildenstern character says the line "Where are you, Sydney?"

```
$ git bisect good
99e83f88f1539c9b45badfaf2685d0e688c85bc3 is the first bad commit
commit 99e83f88f1539c9b45badfaf2685d0e688c85bc3
Author: Hans-Kristian Arntzen <maister@archlinux.us>
Date:   Sat Dec 15 22:19:03 2018 +0100

    Support SSAA with 16x IR.

    64-tap resolve shader, why not?

 .../glsl/prebuilt/resolve.unscaled.16.comp.inc     | 284 +++++++++++++++++++++
 parallel-psx/glsl/rebuild_shaders.sh               |   1 +
 parallel-psx/glsl/resolve.comp                     |   8 +
 parallel-psx/renderer/renderer.cpp                 |   5 +-
 parallel-psx/renderer/renderer_pipelines.hpp       |   4 +
 rsx/rsx_lib_vulkan.cpp                             |   4 -
 6 files changed, 301 insertions(+), 5 deletions(-)
 create mode 100644 parallel-psx/glsl/prebuilt/resolve.unscaled.16.comp.inc
```

**Comment by Themaister** [comment] 2019-12-18 20:32
Should be fixed on master now. Found a precision related bug.

**Comment by Sanaki** [comment] 2019-12-18 22:51
Cannot produce the bug anymore on that line in Vagrant Story at 16x. Looks good!

**Comment by rz5** [comment] 2019-12-19 09:36
I could replicate this bug in Crash Bandicoot Warped, Metal Gear Solid and Vagrant Story.
As of commit https://github.com/libretro/beetle-psx-libretro/commit/8ed15d2090ec41ec95cf7d042aa88aa5519c9058, this bug seems to be fixed on both of my systems.

Specifically, texture corruption would occur on a GTX 970 with 16x upscale and on an AMD R330 with 4x and 8x upscale.

I'm closing this and labeling/closing the other related issues as duplicates: #524, #529

If this bug still happens for anybody, say so and this can be reopened.

**Closed by rz5** 2019-12-19 09:36 UTC
Labels: vulkan

**Comment by Illynir** [comment] 2019-12-19 14:18
It's fixed for me too, amazing work, guys. Thanks. :)
