### ISSUE TITLE
Black screen when scaling on Vulkan

### ISSUE THREAD

**Issue by HoJo215** [libretro/beetle-psx-libretro#617] opened 2020-02-24 00:08 UTC
So with Vulkan on. When scaling above 0 to hide black borders outside of an overlay, the screen goes black.

Metal gear for instance runs without glitching the real-time fmv with Vulkan but if you try to scale out the black borders, you get a black screen.

Can it be fixed the way Gl scales for Vulkan?

**Comment by ggdrt** [comment] 2020-02-24 01:11
I don't quite understand what you are trying to say.

Can you please fill out the issue template that is presented to you when creating a new issue and provide screenshots where possible?

**Comment by HoJo215** [comment] 2020-02-24 16:54
## Description

Black screen when upscaling when using Vulkan video render.

### Expected behavior

Crop out horizontal black borders on some games.

### Actual behavior

Screen goes black.

### Steps to reproduce the bug

Set video render to vulkan
Go to video / scaling option
Set aspect ratio to custom
Scale the "Custom Aspect Ratio Y Pos." upwards (pressing left) above 0 (zero)

### Version/Commit

1.8.5 - Beetle PSX HW (0.9.44.1 77e90d5)

**Comment by ggdrt** [comment] 2020-02-24 18:36
I don't know how that setting in the frontend works, so some other developer will have to chime in on that.

You can use the core options to crop black borders in games. Take a look at the `Crop Horizontal Overscan`, `Horizontal Image Offset`, and `Initial/Last Scanline` core options.

**Comment by ggdrt** [comment] 2020-02-27 15:25
@HoJo215 I'm unable to reproduce your bug using RetroArch on Windows 10. Your issue template is incomplete and doesn't provide us your core options setting and environment information, both of which are useful for us to determine if this is a platform or frontend specific issue.

Please also confirm if the core options listed in the previous comment are suitable for cropping the game's borders.

**Comment by ggdrt** [comment] 2020-03-13 21:56
Closing issue due to lack of follow up and limited information to work off of. The core options mentioned above should suffice for hiding black borders in games.

**Closed by ggdrt** 2020-03-13 21:56 UTC
