### ISSUE TITLE
Unable to full stretch screen under Vulkan (no option available).

### ISSUE THREAD

**Issue by backgamon** [libretro/beetle-psx-libretro#564] opened 2019-11-15 15:50 UTC
## Description
Before last update i can full stretch for fit all the screen:
![full](https://user-images.githubusercontent.com/39404647/68955926-525e0080-07c7-11ea-872a-fcfa949187e5.jpg)

[Description of the bug]
Now i have black border on top/bottom and side of screen:
![black](https://user-images.githubusercontent.com/39404647/68955972-6a358480-07c7-11ea-9d06-6ffa34b001cf.jpg)

### Steps to reproduce the bug

Just launch the latest retroarch (1.8.1) with Psx Beetle HW latest updated [few hours ago, both core (Ogl/Vulkan)].
### Bisect Results

The core available before (yesterday) doesn't have any problem of black border.

### Environment information

- OS: Windows 10 Pro X64 1909
- GPU: Gigabyte 2070 RTX 8 OC - 441.20

**Comment by hizzlekizzle** [comment] 2019-11-15 16:04
This is working as intended and more accurate to the hardware (r5 and ggdrt have been doing a lot of work lately to make the screen geometry behavior more accurate in the hardware renderers). However, there should be cropping options in the core options that you can use to hide the black bars.

**Comment by backgamon** [comment] 2019-11-15 16:09
I tryed some of the options of cropping, but without luck...no change :/

**Comment by backgamon** [comment] 2019-11-15 16:40
> 
> 
> I tryed some of the options of cropping, but without luck...no change :/

EDIT:
Ok, i found how to stretch with OGL...but not for Vulkan  :(

**Comment by rz5** [comment] 2019-11-15 19:03
@backgamon - With "Crop Overscan" off, you will see vertical and horizontal overscan and this is what would be there with real hardware. This is accurate behavior.

If you turn on "Crop Overscan", you can get rid of the side black bars on all of the renderers.

The horizontal overscan is simple to get rid of in NTSC content, less simple for PAL for the HW renderers handle it just fine without the user needing to do manual offset adjustments.

Vertical overscan is complicated, especially for PAL content. 
For NTSC content, games can draw up to 240 lines (ignoring 480 interlaced settings). Whether or not the full 240 lines are used to draw colors is up to the game because it's the game that configures the PSX GPU. 
Some games can opt to only use less lines, which frees up the PSX VRAM for other uses. When a game does this, it usually configures PSX GPU such that the smaller amount of lines are padded to 240 when drawn on-screen.

For PAL content, it's worse. Now we have up to 288 lines, many games seem to be naive NTSC-to-PAL ports and aren't redesigned to take advantage of the extra lines and because beetle-psx displays all those 288 lines, you get even bigger top/bottom black bars.

Even if we peek inside the PSX GPU to check the vertical display range values, that might still be insufficient to crop the height "perfectly". Plus, I think it would make aspect ratio correction very difficult.

If you're using RetroArch, you can always use the video options and use custom resolutions to zoom in and crop it to your liking.

I'll ping @ggdrt for further thoughts and corrections on what I wrote.

**Comment by backgamon** [comment] 2019-11-16 19:40
Well..
I found how to crop screen under OGL, but value seem to change game to game...not really user friendly...
Under Vulkan i didn't found the same thing of OGL...
Just for know, adding a switch for old or new method aren't possible?
I guess some ppl doesn't care about 'pixel perfect' (i'm on), i'use emulator mainly for the ehancement provided....If i want 'reality' i use the true console.
After i respect any progress under emu, before i'm not really interressed by Bsnes...but HD render for mode 7 changed my mind :)
---
Currently i'm back with a old version of retroarch (1.7.7) and a little oldest (07/19) psx beetle core, i think stay with for a while....with corrupted gfx in some cases :/

**Comment by Papermanzero** [comment] 2019-11-17 22:14
https://github.com/libretro/beetle-psx-libretro/issues/566

**Comment by Papermanzero** [comment] 2019-11-17 22:15
@backgamon 
Can you share your latest version.
I have the same issue with vulkan, but i deleted the old version.

**Comment by ggdrt** [comment] 2019-11-18 05:32
I've pushed an implementation of the initial/last scanline core options for the Vulkan renderer. These options, which previously had no effect until now, should be used to crop vertical borders. The build should be available from the buildbot some time within the next day or so.

> Well..
> I found how to crop screen under OGL, but value seem to change game to game...not really user friendly...
> Under Vulkan i didn't found the same thing of OGL...
> Just for know, adding a switch for old or new method aren't possible?
> I guess some ppl doesn't care about 'pixel perfect' (i'm on), i'use emulator mainly for the enhancement provided....If i want 'reality' i use the true console.

Unfortunately that's just how it is, and you'll find the same behavior with the software renderer. You have to understand that many games relied on certain psx gpu functionality for effects such as screen shaking or proper letterboxing. Without these recent additions to the hardware renderers, these games do not animate properly. This is something that we can not really compromise on.

**Comment by tabnk** [comment] 2019-11-18 09:30
Similar issue. Enable widescreen look even more weirdly.

**Comment by backgamon** [comment] 2019-11-18 11:37
> 
> 
> @backgamon
> Can you share your latest version.
> I have the same issue with vulkan, but i deleted the old version.

I use that version:

https://mega.nz/#!FvwE0CaK!0do7oj3lM6cRSxbT97VFManC8L0qnZz6ovIMSXahnC8

I use with Retroarch 1.7.7 because i can't change driver after a while on the latest RA :/

**Comment by Papermanzero** [comment] 2019-11-18 12:57
> I've pushed an implementation of the initial/last scanline core options for the Vulkan renderer. These options, which previously had no effect until now, should be used to crop vertical borders. The build should be available from the buildbot some time within the next day or so.
> 
> > Well..
> > I found how to crop screen under OGL, but value seem to change game to game...not really user friendly...
> > Under Vulkan i didn't found the same thing of OGL...
> > Just for know, adding a switch for old or new method aren't possible?
> > I guess some ppl doesn't care about 'pixel perfect' (i'm on), i'use emulator mainly for the enhancement provided....If i want 'reality' i use the true console.
> 
> Unfortunately that's just how it is, and you'll find the same behavior with the software renderer. You have to understand that many games relied on certain psx gpu functionality for effects such as screen shaking or proper letterboxing. Without these recent additions to the hardware renderers, these games do not animate properly. This is something that we can not really compromise on.

Thanks a lot for the explanation. 
The effort is highly appreciated. Thanks a lot.

I guess if u enable the cropping together with initial/last line for the vulkan renderer then the original behavior can be reproduced and everyone is happy. The important is though to keep the aspect ratio of the games.

Will try later the newest version and give feedback.

**Comment by Papermanzero** [comment] 2019-11-18 13:39
> 
> 
> > @backgamon
> > Can you share your latest version.
> > I have the same issue with vulkan, but i deleted the old version.
> 
> I use that version:
> 
> https://mega.nz/#!FvwE0CaK!0do7oj3lM6cRSxbT97VFManC8L0qnZz6ovIMSXahnC8
> 
> I use with Retroarch 1.7.7 because i can't change driver after a while on the latest RA :/

thanks it is working!

**Comment by bigol83** [comment] 2019-11-18 20:39
With the newest core update you can now stretch fullscreen but there still is a thin border on the left side while using widescreen mode. 

Vulkan renderer

![Metal Gear Solid](https://user-images.githubusercontent.com/38129260/69091806-5732e680-0a4b-11ea-803d-ef3c7c70deeb.png)

**Comment by ggdrt** [comment] 2019-11-19 04:06
I'm not sure why your thin border is on the left, but I can confirm that the NTSC-U version of Metal Gear Solid configures the gpu in a way that results in a single pixel wide border on the right when horizontal overscan is cropped. This is also unfortunately accurate behavior, since the current horizontal overscan cropping is configured for properly centered games, which MGS does not seem to be.

At this point, there are two ways I think we can go with this: either we add in a toggle option that attempts to automatically center games but may not work for all games and prevent certain screen effects from animating, or we add in a different option that allows users to manually set the relative horizontal offset (in units of gpu cycles) but can not accommodate borders properly for poorly/strangely programmed games that constantly change its gpu horizontal configuration between scenes.

The software renderer opts for the latter because it better retains accuracy by allowing all screen effects to still animate.

**Comment by rz5** [comment] 2019-11-19 04:49
It's surprising to see that in an NTSC-U game since it's way more common in PAL games.

The horizontal cropping is a good "best effort" attempt that unfortunately needs tweaking in a lot of PAL stuff and apparently in some NTSC stuff as well.

Reading nocash's notes on miscentered PAL games and thinking out loud here: perhaps one possible approach to get it centered while also not preventing screen animations that work via display ranges would be to:
1) Ensure cropping and pixel offset values are done only on new display modes;
2) When calculating the pixel offset that will center the picture after cropping, we take the status of the horizontal display range into account.

Point nr2 assumes there exists a pair of values that symbolized "centered" content. With that assumption in place, we could re-center the picture once per new display mode.

If that assumption is false...well, no dice I guess.

**Comment by bigol83** [comment] 2019-11-19 09:37
> I'm not sure why your thin border is on the left, but I can confirm that the NTSC-U version of Metal Gear Solid configures the gpu in a way that results in a single pixel wide border on the right when horizontal overscan is cropped. This is also unfortunately accurate behavior, since the current horizontal overscan cropping is configured for properly centered games, which MGS does not seem to be.
> 
> At this point, there are two ways I think we can go with this: either we add in a toggle option that attempts to automatically center games but may not work for all games and prevent certain screen effects from animating, or we add in a different option that allows users to manually set the relative horizontal offset (in units of gpu cycles) but can not accommodate borders properly for poorly/strangely programmed games that constantly change its gpu horizontal configuration between scenes.
> 
> The software renderer opts for the latter because it better retains accuracy by allowing all screen effects to still animate.

Thanks for your answer. This is Metal Gear Solid Pal version

I tried the same settings with Opengl renderer and there is no thin border

![Metal Gear Solid ogl](https://user-images.githubusercontent.com/38129260/69134785-57b59680-0ab8-11ea-84f7-65f65eb0df35.png)

**Comment by ggdrt** [comment] 2019-11-19 10:43
Yeah that's because the GL renderer currently completely ignores the psx gpu's horizontal configuration when the crop overscan option is on. It's not supposed to work that way and it just happens to not show the black bar because I haven't yet had time to fix this crop overscan issue. It turns out the PAL version of Metal Gear Solid is miscentered two pixels to the right, which both the software and Vulkan renderers replicate accurately.

I think in the short term, we could offer an experimental core option that allows the image to be horizontally offset by a user-specified number of gpu cycles, similar to the software core's image_offset option but more accurate.

**Comment by ggdrt** [comment] 2019-11-20 08:22
The latest changes on `master` that should be available on the buildbot soon will allow you to horizontally adjust the image on the OpenGL and Vulkan renderers. For games that are permanently miscentered, it's probably best to save an override. Some PAL games are notoriously miscentered by quite a lot and the currently provided range for `beetle_psx_hw_image_offset_cycles` through the UI might not be enough. If that's the case, provide us some examples for reference and we'll see what we can do about it.

The core options have also been reordered so that similar options are grouped together for better usability.

As a fair warning, things are still under active development and we're actively trying to balance accuracy and user friendliness, which are sometimes orthogonal to one another. Thank you for your patience.

**Comment by Papermanzero** [comment] 2019-11-20 09:30
What options for scanlines do you use for Pal games to upscale them to fullscreen?

**Comment by rz5** [comment] 2019-11-20 20:17
@Papermanzero - If you're asking for a pair of numbers that would perfectly crop PAL content vertical overscan, that does not exist. If you want specific examples:

* The PAL BIOS "Sony" logo's vertical overscan can be "cropped" if you use 23 to 261 as initial/last scanlines (239 colored lines total).
* In Metal Gear Solid PAL, in the menus, use 16 to 269 (254 colored lines) but in-game you have to reduce cropping and use 15 to 270 (256 colored lines).
* In Crash Bandicoot 3 PAL, use 17 to 257 (256 colored lines).
* In Tekken 3 PAL, use 23 to 262 (240 colored lines).

So, as you see, there isn't really an initial/last scanline pattern that applies to these 4 examples. Maybe there's something to be said about auto-cropping the scanlines from 288 to 256 lines, but then how would we reliably find the first "colored" line i.e. that the game draws to it?

This is what is meant by PAL content being mis-centered. And the naive solution (ignoring vertical display ranges) causes bugs that @ggdrt has sought to correct.

**Comment by Papermanzero** [comment] 2019-11-20 23:30
Thanks that is what I wanted to know. It is interesting from a PAL vs NTSC standardization point of view. Even the 23/261 is a strange number according to PAL conversion standards. but those are the same numbers which I am using.

**Comment by tabnk** [comment] 2019-11-21 10:05
Even with latest build, Tekken 3 and SFEX 2 PLUS widescreen mode still got TOP/BOTTOM black bar

**Comment by ggdrt** [comment] 2019-11-21 11:10
Have you attempted to use the "initial/last scanline" core options at all? I mentioned those options in this thread before you commented the first time.

**Comment by tabnk** [comment] 2019-11-21 12:26
Both are NTSC GAMES. Already max initial = 0 AND last = 239.

**Comment by Papermanzero** [comment] 2019-11-21 15:13
And why are u not modifying the values for NTSC lines to get rid of the borders?
U can save a config file for the game.

**Comment by ggdrt** [comment] 2019-11-26 16:20
I'm going to consider this resolved with the recent configurable options added for the Vulkan renderer. The current default behavior is accurate while also allowing users to fine-tune the outputted image to their liking. Improvements such as auto-centering could still be made but are not planned for the time being.

**Closed by ggdrt** 2019-11-26 16:20 UTC
