### ISSUE TITLE
[Vulkan] Final Fantasy 8 Hardware Core becomes unstable, crashes after entering room

### ISSUE THREAD

**Issue by xeropresence** [libretro/beetle-psx-libretro#445] opened 2018-11-14 09:44 UTC
# First and foremost consider this:
Bug is not reproducible with mednafen, or the software renderer.
    
## Description

When entering the train compartment containing zell after leaving balamb to dollot the hardware renderer stops working correctly. Attempting to load a a save state results in corrupted textures. While the display stops rendering, the gameplay does sound like its continuing on in the background.
### Expected behavior

[What you expected to happen]

Graphics to continue running properly

[What is actually happening]

ff8 beetle vulkan hw render
https://streamable.com/twrfj
ff8 beetle ogl hw render
https://streamable.com/vsla4
ff8 beetle sw render
https://streamable.com/nj488
ff8 mednafen 
https://streamable.com/6w7zz

### Steps to reproduce the bug

[Final Fantasy VIII Disc1.1.zip](https://github.com/libretro/beetle-psx-libretro/files/2580066/Final.Fantasy.VIII.Disc1.1.zip)

Load save game
Move into next compartment
Move into next compartment

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
[If you're using RetroArch, after the core has started, this information is on the bottom left]

- Beetle PSX: RetroArch Beetle PSX 0.9.44.1 74bd755

### Core options
No core options were changed for the recorded videos

### Environment information

- OS: Windows 10 1809
- GPU: 1080 ti 416.34

**Comment by xeropresence** [comment] 2018-11-14 09:53
Interestingly , if I changed the cpu frequency scaling to ~70% the issue does not occur.

**Comment by rz5** [comment] 2018-11-16 04:52
I can confirm that graphical glitches do happen on the vulkan renderer.

**Comment by iCatButler** [comment] 2018-12-01 21:56
The same bug occurs in the starting forest scene of Chrono Cross' attract mode.

It appears to have been introduced when the vertex size was increased to include UV limits (to clamp sampling to the edges of primitives). If I remove some of those new member variables, making the vertices smaller, or increase the block size of the Vulkan Device's PerFrame vbo_chain allocator then the glitching doesn't occur.

It may have been an existing error that went undetected and it's writing over the end of the buffer now that the vertices are larger.

**Comment by theoldsport** [comment] 2018-12-02 08:37
@iCatButler related to #422? Vertex explosions tending to occur on Vulkan, generally when cpu overclocking enabled

**Comment by iCatButler** [comment] 2018-12-02 08:54
@theoldsport it could be. These changes came in on the 20th August (7a4177f9d8947cca38f4135d3b934cea4366f83a), which is a couple of weeks before that issue was opened.

It's happening for me without any overclocking enabled, it's interesting that it is influenced by that though.

**Comment by xeropresence** [comment] 2018-12-02 09:01
I can reproduce it in a few spots in FF8 with overclocking turned on as well, disabling it and it will no longer occur. The issue in the op happens with OC off.

**Comment by iCatButler** [comment] 2018-12-03 17:34
I've got a theory on what's happening, although I'm not too familiar with how the wider emulator works so could be completely wrong.

From testing the error only happens when the Vulkan Device's PerFrame vbo_chain allocator has extended beyond its initially allocated block. This makes sense as reducing vertex size or increasing the block size means it will fit more vertices before needing extended.

I assume this happens when the emulator attempts to render more triangles in a single "frame" than will fit into the default block. In this FF8 scene and CC's attract mode the scene rendering is optimised enough to do this normally, but overclocking the emulated CPU allows more rendering to occur in a single "frame" than normal so it can also overfill the buffer.

I say "frame" because I think this is actually a refresh (i.e. every 16.6ms) rather than the game's frame rate (16.6ms, 33.3ms or whenever it's done). So the game can be half way through rendering a frame internally when the `discard` is called on the PerFrame vbo allocator during `rsx_intf_prepare_frame`, resetting allocation to the start of the first buffer (and preventing the game from ever causing it to extend).

I'm not sure why this buffer extension behaviour should cause the bug though. I assume all vulkan commands are flushed each "frame"/refresh so the contents of the buffer is no longer needed, otherwise the overwriting behaviour that normally occurs would be causing errors when old draw commands tried to access overwritten data.

**Comment by iCatButler** [comment] 2018-12-03 21:30
I figured it out :)

It appears to be a bug in the `ChainAllocator` class itself. Whenever it allocates a new block it updates the `host` pointer to point to the start of it. However, when it resets on `discard()` it doesn't change the pointer back to the first block, so in the following frame it allocates memory from the first block while pointing to the second. 
All the data for the new frame is written to the wrong buffer. Then, when it switches to the second block it actually points back to the beginning of that same block again and starts overwriting the previously written data.

I'll fix up the class to update the `host` pointer properly and get it checked in once I've made sure I'm doing this correctly (it's a bit hacky at the moment).

**Comment by iCatButler** [comment] 2018-12-04 20:35
@xeropresence The fix should now be in the latest build if you'd like to test it.

**Comment by xeropresence** [comment] 2018-12-04 21:10
Looks like its resolved. Also resolved an issue when using the cpu overclock and having some battle sequences lockup. I'll have to recompile the core without https://github.com/libretro/beetle-psx-libretro/commit/8d15a7823c887fb46db43b59c0f11b1fb35905f6 for the time being to avoid https://github.com/libretro/beetle-psx-libretro/issues/451#issuecomment-443150674

**Closed** 2018-12-04 22:03 UTC
