### ISSUE TITLE
[Vulkan/OpenGL] Numerous graphical issues in King's Field (Japan)

### ISSUE THREAD

**Issue by kurayami6** [libretro/beetle-psx-libretro#307] opened 2018-02-17 22:51 UTC
i5
GTX 970
Windows 7
Beetle PSX HW 0.9.44.1 94bf8ae
Beetle PSX software 0.9.44.1 1a9ad36

King's Field 1 has numerous problems in Beetle PSX HW. All settings default. Happens with both Vulkan and OpenGL. These problems are not present when using the software core. 

The pause screen does not appear

![king s field japan -180218-093329](https://user-images.githubusercontent.com/31968468/36346338-d2dfcada-1490-11e8-8243-5e391255a49e.png)

The menu screen does not appear

![king s field japan -180218-093404](https://user-images.githubusercontent.com/31968468/36346340-de1c99b4-1490-11e8-85af-f0400b9dde1f.png)

Sign text does not appear

![king s field japan -180218-093341](https://user-images.githubusercontent.com/31968468/36346344-e8a44f08-1490-11e8-854a-6301da6d6a92.png)

Transparent walls

![king s field japan -180218-093437](https://user-images.githubusercontent.com/31968468/36346345-f133f9b6-1490-11e8-8fae-15f457508013.png)

As well as constant flickering textures.

For comparison, here are those things rendering correctly with the software core

![king s field japan -180218-094027](https://user-images.githubusercontent.com/31968468/36346357-210316b8-1491-11e8-9b4a-d41a998460fe.png)

![king s field japan -180218-094009](https://user-images.githubusercontent.com/31968468/36346359-25bca5d4-1491-11e8-9834-b7cf761ad76a.png)

![king s field japan -180218-094021](https://user-images.githubusercontent.com/31968468/36346360-296c739e-1491-11e8-8c84-974b141d27bf.png)

**Comment by saftle** [comment] 2018-03-03 07:29
When switching between GL and Vulkan, was the RetroArch driver and the renderer set to the same value? Otherwise, the renderer will always fallback to whatever is set as the RetroArch driver.

**Comment by twinaphex** [comment] 2018-07-18 09:04
Confirmed.

Vulkan shows a similar amount of bugs, but draws more of the HUD. Looks like culling/multipass issues.

Only the software renderer draws the game correctly.

**Comment by Hypsicratea** [comment] 2019-11-05 23:15
I have found that using the Vulkan renderer with GTE Overclock enabled and GPU Rasterizer Overclock to 2x solves almost all of the graphical glitches, with the exception of missing sign text and missing dialogue text (when talking to characters).

**Comment by rz5** [comment] 2019-11-05 23:49
@Hypsicratea - Hi, thanks for the feedback. Could you please write out the state of your core options?
Specifically the 'software framebuffer' option as that one is notorious for causing timing issues and missing effects.

**Comment by lukie123** [comment] 2019-11-09 09:15
I can also confirm that GPU Rasteriser Overclock set to 2x and above solves the flickering, transparent walls, and missing HUD display, however as Hypsicratea pointed out, sign text, dialogue text, and the pause menu are all missing still. I would also like to point out that GTE Overclock enabled doesn't solve the issues, it doesn't effect anything actually. The software framebuffer option also doesn't effect anything.

Unrelated to the graphical issues, the fan translated patch of the game crashes when attempting to save in-game, however this doesn't happen when using the PCSX Rearmed core. The original, Japanese, non-fan translated game however doesn't have this issue, the game can save no matter which core is being used.

**Comment by ggdrt** [comment] 2020-03-06 10:20
@kurayami6 There was a recent patch that should have fixed these sort of issues, can you verify if they are fixed for you on the hardware renderers at stock settings?

**Comment by lukie123** [comment] 2020-03-07 16:31
Hi, I just tested the non-patched Japanese version on stock settings (Beetle PSX HW & Vulkan) and can confirm that the flickering and transparent walls are gone and that the pause menu, the character menu, the HUD, and the sign texts all render as they should.

On gl, I'm not sure if the flickering and transparent walls were present before but they are no longer present. However, the pause menu, character menu, sign texts, and HUD still do not render properly

**Comment by ggdrt** [comment] 2020-03-13 22:55
@lukie123 Thanks for following up. Can you create a new issue for those GL renderer bugs?

I'll go ahead and close this issue as the bug(s) in common for the GL and Vulkan renderers were caused by the GP1(05h) command not being emulated at the time, which the patches last month implemented.

**Closed by ggdrt** 2020-03-13 22:55 UTC
Labels: graphics bugs, opengl, vulkan
