### ISSUE TITLE
Beetle PSX HW crashes when trying to use multiplied resolution

### ISSUE THREAD

**Issue by JohnTitor177** [libretro/beetle-psx-libretro#164] opened 2017-03-05 13:11 UTC
x2 and x4 crash Retroarch
i'm using 1.4.1 stable with latest beetle psx hw core (at the time of posting), but it crashes in latest retroarch nightly (again, at the time of posting) as well
happens on both x86 and x86_64 builds, and i'm using Windows

UPD: after further testing i found out that this only happens when retroarch driver is set to gl (this happens on both vulkan and opengl settings for rendering in Beetle)
if you set retroarch driver to vulkan, vulkan setting for rendering in Beetle works, opengl setting crashes
if you go back to gl setting for retroarch driver, beetle doesn't crash on both vulkan and opengl settings for rendering, but glitches horribly.
(this was tested on x86 build)

**Comment by wingedonezero** [comment] 2017-04-04 23:09
I can confirm this having same problem. Have to have both set the same in order for it to use the multiplier. Although i haven't got opengl to work with multiplier crashes there no matter the setting. Using 1.4.1 64bit.

**Comment by SpaceMonkey-92** [comment] 2017-06-04 19:17
Same problem here, unfortunately for me I can't even test out the vulkan renderer since setting the retroarch driver to Vulkan causes Retroarch to crash any time I attempt to open the quick menu.

**Comment by JacobAL** [comment] 2017-07-06 10:11
I have noticed this problem but only when trying to use the software renderer, even when using the software only core.

**Comment by shinra358** [comment] 2017-07-10 00:40
This only happens with me when using the scalefx x9 shader.

**Comment by rz5** [comment] 2017-07-27 22:24
@JohnTitor177 @shinra358 Could you please check if it still happens with the latest commits?

**Comment by shinra358** [comment] 2017-07-27 23:00
Ok, ill test when i get off work.

**Comment by shinra358** [comment] 2017-07-28 03:07
I didn't know if you meant retroarch or just the core. So I updated both with the latest of the nightly builds and through download through the core updater. I only tested the hardware version of this core but sadly, it still crashes.

**Comment by shinra358** [comment] 2017-08-04 22:54
So since there hasn't been any more responses, I took it upon myself to finally test the crashes that dealt with playing through the xmb. The newest version fixes that problem. VB nor the sega games I mentioned above no longer crash when starting through the xmb. So now only the psx scalefx+>1x resolution crashes remain.

**Comment by rz5** [comment] 2017-08-05 01:17
@shinra358 The texture filter stuff still causes crashes? If so, just open up another issue to track that.
@JohnTitor177 - Can you confirm that the upscaling no longer crashes for you either? Feel free to close the issue if it's all good.

**Comment by shinra358** [comment] 2017-08-05 02:41
I actually thought this was the other post. My last commit was meant for the other post. My bad.

**Comment by JacobAL** [comment] 2017-08-05 08:21
Yeah, working fine now. I can put it back into software mode again and can scale resolution in software mode.
Thanks.

**Comment by rz5** [comment] 2017-10-13 00:04
@JohnTitor177 I'll be closing this now as I haven't been getting crashes. Do verify if it's good for you too.

**Closed by rz5** 2017-10-13 00:04 UTC
