### ISSUE TITLE
HW Shared Context Enable graphical corruption

### ISSUE THREAD

**Issue by JuanVCS** [libretro/beetle-psx-libretro#100] opened 2016-10-01 19:30 UTC
With this option set to ON I get graphical glitches on all games I tried:

![intelligent qube-161001-162518](https://cloud.githubusercontent.com/assets/3089037/19016574/576defbe-87f4-11e6-9d80-967368e427cd.png)
![iss deluxe-161001-162859](https://cloud.githubusercontent.com/assets/3089037/19016570/576d1418-87f4-11e6-9728-822210c2f67e.png)
![metal gear solid-161001-162217](https://cloud.githubusercontent.com/assets/3089037/19016571/576d0964-87f4-11e6-8554-20e2ca104c42.png)
![metal gear solid-161001-162248](https://cloud.githubusercontent.com/assets/3089037/19016572/576d6bfc-87f4-11e6-950c-5d4c349021b7.png)
![tekken 3-161001-162345](https://cloud.githubusercontent.com/assets/3089037/19016573/576d9d8e-87f4-11e6-943e-c61802504c74.png)
![tekken 3-161001-162952](https://cloud.githubusercontent.com/assets/3089037/19016575/57a8ea56-87f4-11e6-8020-1f5bdaa8148e.png)

**Comment by simias** [comment] 2016-10-01 19:50
Thank you for the report.

You shouldn't use this option with hw renderer, it probably performs worse and doesn't add anything. Shared context is meant as a workaround for cores that don't play well with RA's opengl context.

That being said it probably shouldn't cause any regression when it's activated. It's probably worth investigating but quite low priority, unless you have any reason for wanting to use shared context with beetle?

**Comment by JuanVCS** [comment] 2016-10-01 20:08
No reason whatsover, just thought I report it in case someone else runs into the same bugs. Had that option enabled for reicast as suggested [here](http://www.libretro.com/index.php/retroarch-1-3-released/).

**Comment by jeremynsl** [comment] 2016-10-04 23:17
Slightly OT but would it be possible to automatically enable this option for cores that require it and disable it for those that don't?  I don't think the average user understands this option and it requires research to know when to enable it or not.

**Comment by simias** [comment] 2016-10-05 08:11
I guess it could be hinted at in the render_callback struct or something like that. @twinaphex what's your opinion?

**Comment by rz5** [comment] 2017-08-18 00:18
Since a couple of versions ago, a core can set a hint to the frontend indicating it needs a shared HW context and it has since been implemented on the OpenLara and Dolphin cores.

Plus, the GL renderer plays well with that option on anyways, I'll close this for now.

**Closed by rz5** 2017-08-18 00:18 UTC
