### ISSUE TITLE
Blank screen when using OpenGL

### ISSUE THREAD

**Issue by Daniel15** [libretro/beetle-psx-libretro#369] opened 2018-07-07 18:38 UTC
I'm hitting a blank screen when using the OpenGL renderer. I can hear the sound from the BIOS, but there's no video

Windows 10.0.17134.137
AMD R9 390

Log:
```
[INFO] RetroArch 1.7.1 (Git 6fc6bfbb24)
[INFO] === Build =======================================
[INFO] Version: 1.7.1
[INFO] Git: 6fc6bfbb24
[INFO] =================================================
[INFO] [Config]: Loading default config.
[INFO] [Config]: loading config from: (null).
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "D:\games\RetroArch\saves\.srm".
[INFO] Redirecting savestate to "D:\games\RetroArch\states\.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.53 Hz.
[INFO] [SoftFilter]: Found plug: 2xBR (2xbr).
[INFO] [SoftFilter]: Found plug: 2xSaI (2xsai).
[INFO] [SoftFilter]: Found plug: Blargg NTSC SNES (blargg_ntsc_snes).
[INFO] [SoftFilter]: Found plug: Darken (darken).
[INFO] [SoftFilter]: Found plug: EPX (epx).
[INFO] [SoftFilter]: Found plug: LQ2x (lq2x).
[INFO] [SoftFilter]: Found plug: Phosphor2x (phosphor2x).
[INFO] [SoftFilter]: Found plug: Scale2x (scale2x).
[INFO] [SoftFilter]: Found plug: Super2xSaI (super2xsai).
[INFO] [SoftFilter]: Found plug: SuperEagle (supereagle).
[INFO] Using 1 threads for softfilter.
[INFO] [Video]: Video @ 640x480
[INFO] [GL]: Found GL context: wgl
[INFO] [GL]: Detecting screen resolution 2560x1440.
[INFO] [WGL]: wglSwapInterval(1)
[INFO] [GL]: Vendor: ATI Technologies Inc., Renderer: AMD Radeon (TM) R9 390 Series.
[INFO] [GL]: Version: 4.5.13497 Compatibility Profile Context 23.20.808.1792.
[INFO] [GL]: Using resolution 640x480
[INFO] [GL]: Default shader backend found: glsl.
[WARN] Rendering context is incompatible with shader type: nul
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[ERROR] [GL]: Failed to parse GLSL shader.
[ERROR] [GL]: Failed to initialize shader, falling back to stock.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [XInput]: Found XInput v1.4.
[INFO] [XInput]: Found controller, user #0
[INFO] [XInput]: Pads connected: 1
[INFO] [DINPUT]: Enumerating joypads ...
[INFO] [DINPUT]: Device #0 PID: {C21D} VID:{046D}
[INFO] [DINPUT]: Done enumerating joypads ...
[INFO] [XInput]: Attempting autoconf for "XInput Controller (User 1)", user #0
[INFO] [DINPUT]: Found XInput pad at index 0 (DINPUT index 0)
[INFO] [XInput]: Found VID/PID (046D/C21D) from DINPUT index 0 for "XInput Controller (User 1)", user #0
[INFO] [XInput]: Attempting autoconf for user #1
[INFO] [XInput]: Attempting autoconf for user #2
[INFO] [XInput]: Attempting autoconf for user #3
[INFO] [XInput]: Attempting autoconf for user #4
[INFO] [XInput]: Attempting autoconf for user #5
[INFO] [XInput]: Attempting autoconf for user #6
[INFO] [XInput]: Attempting autoconf for user #7
[INFO] [XInput]: Attempting autoconf for user #8
[INFO] [XInput]: Attempting autoconf for user #9
[INFO] [XInput]: Attempting autoconf for user #10
[INFO] [XInput]: Attempting autoconf for user #11
[INFO] [XInput]: Attempting autoconf for user #12
[INFO] [XInput]: Attempting autoconf for user #13
[INFO] [XInput]: Attempting autoconf for user #14
[INFO] [XInput]: Attempting autoconf for user #15
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [Autoconf]: 63 profiles found.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: win32
[INFO] XAudio2: Requesting 64 ms latency, using 64 ms latency.
[INFO] [autoconf]: selected configuration: D:\games\RetroArch\autoconfig\xinput\XInput_Controller_User_1.cfg
[INFO] [Menu]: Found menu display driver: "menu_display_gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0000000000883880
[WARN] Input device ID 517 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
[INFO] SRAM will not be saved.
[INFO] [GL]: VSync => on
[INFO] [WGL]: wglSwapInterval(1)
[INFO] [GL]: VSync => on
[INFO] [WGL]: wglSwapInterval(1)
[INFO] Updating firmware status for: D:\games\RetroArch\cores\mednafen_psx_hw_libretro.dll on D:\games\RetroArch\system
[WARN] Firmware missing: scph5500.bin
[INFO] Using content: D:\games\ROMS\PSX\Crash_Bandicoot.cue.
[INFO] arg #0: retroarch
[INFO] arg #1: D:\games\ROMS\PSX\Crash_Bandicoot.cue
[INFO] arg #2: -s
[INFO] arg #3: D:\games\RetroArch\saves
[INFO] arg #4: -S
[INFO] arg #5: D:\games\RetroArch\states
[INFO] arg #6: -c
[INFO] arg #7: D:\games\RetroArch\retroarch.cfg
[INFO] arg #8: -L
[INFO] arg #9: D:\games\RetroArch\cores\mednafen_psx_hw_libretro.dll
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] Set config file to : D:\games\RetroArch\retroarch.cfg
[INFO] RetroArch 1.7.1 (Git 6fc6bfbb24)
[INFO] Redirecting save file to "D:\games\RetroArch\saves\Crash_Bandicoot.srm".
[INFO] Redirecting savestate to "D:\games\RetroArch\states\Crash_Bandicoot.state".
[INFO] === Build =======================================
[INFO] Version: 1.7.1
[INFO] Git: 6fc6bfbb24
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "D:\games\RetroArch\cores\mednafen_psx_hw_libretro.dll"
[INFO] [overrides] no core-specific overrides found at D:\games\RetroArch\config\Beetle PSX HW\Beetle PSX HW.cfg.
[INFO] [overrides] no game-specific overrides found at D:\games\RetroArch\config\Beetle PSX HW\Crash_Bandicoot.cfg.
[INFO] Shaders: preset directory: D:\games\RetroArch\shaders\presets
[INFO] Shaders: no game-specific preset found at D:\games\RetroArch\shaders\presets\Beetle PSX HW\Crash_Bandicoot.cgp.
[INFO] Shaders: no game-specific preset found at D:\games\RetroArch\shaders\presets\Beetle PSX HW\Crash_Bandicoot.glslp.
[INFO] Shaders: no parent-dir-specific preset found at D:\games\RetroArch\shaders\presets\Beetle PSX HW\PSX.cgp.
[INFO] Shaders: no parent-dir-specific preset found at D:\games\RetroArch\shaders\presets\Beetle PSX HW\PSX.glslp.
[INFO] Shaders: no core-specific preset found at D:\games\RetroArch\shaders\presets\Beetle PSX HW\Beetle PSX HW.cgp.
[INFO] Shaders: no core-specific preset found at D:\games\RetroArch\shaders\presets\Beetle PSX HW\Beetle PSX HW.glslp.
[INFO] Environ SET_VARIABLES.
[INFO] Per-Game Options: game-specific core options found at D:\games\RetroArch\config\Beetle PSX HW\Crash_Bandicoot.opt
[INFO] Environ SET_CONTROLLER_INFO.
[INFO] Controller port: 1
[INFO]    PlayStation Controller (ID: 1)
[INFO]    DualShock (ID: 517)
[INFO]    Analog Controller (ID: 261)
[INFO]    Analog Joystick (ID: 773)
[INFO]    Guncon / G-Con 45 (ID: 260)
[INFO]    Justifier (ID: 516)
[INFO]    Mouse (ID: 258)
[INFO]    neGcon (ID: 1029)
[INFO]    (null) (ID: 0)
[INFO] Controller port: 2
[INFO]    PlayStation Controller (ID: 1)
[INFO]    DualShock (ID: 517)
[INFO]    Analog Controller (ID: 261)
[INFO]    Analog Joystick (ID: 773)
[INFO]    Guncon / G-Con 45 (ID: 260)
[INFO]    Justifier (ID: 516)
[INFO]    Mouse (ID: 258)
[INFO]    neGcon (ID: 1029)
[INFO]    (null) (ID: 0)
[INFO] Controller port: 3
[INFO]    PlayStation Controller (ID: 1)
[INFO]    DualShock (ID: 517)
[INFO]    Analog Controller (ID: 261)
[INFO]    Analog Joystick (ID: 773)
[INFO]    Guncon / G-Con 45 (ID: 260)
[INFO]    Justifier (ID: 516)
[INFO]    Mouse (ID: 258)
[INFO]    neGcon (ID: 1029)
[INFO]    (null) (ID: 0)
[INFO] Controller port: 4
[INFO]    PlayStation Controller (ID: 1)
[INFO]    DualShock (ID: 517)
[INFO]    Analog Controller (ID: 261)
[INFO]    Analog Joystick (ID: 773)
[INFO]    Guncon / G-Con 45 (ID: 260)
[INFO]    Justifier (ID: 516)
[INFO]    Mouse (ID: 258)
[INFO]    neGcon (ID: 1029)
[INFO]    (null) (ID: 0)
[INFO] Controller port: 5
[INFO]    PlayStation Controller (ID: 1)
[INFO]    DualShock (ID: 517)
[INFO]    Analog Controller (ID: 261)
[INFO]    Analog Joystick (ID: 773)
[INFO]    Guncon / G-Con 45 (ID: 260)
[INFO]    Justifier (ID: 516)
[INFO]    Mouse (ID: 258)
[INFO]    neGcon (ID: 1029)
[INFO]    (null) (ID: 0)
[INFO] Controller port: 6
[INFO]    PlayStation Controller (ID: 1)
[INFO]    DualShock (ID: 517)
[INFO]    Analog Controller (ID: 261)
[INFO]    Analog Joystick (ID: 773)
[INFO]    Guncon / G-Con 45 (ID: 260)
[INFO]    Justifier (ID: 516)
[INFO]    Mouse (ID: 258)
[INFO]    neGcon (ID: 1029)
[INFO]    (null) (ID: 0)
[INFO] Controller port: 7
[INFO]    PlayStation Controller (ID: 1)
[INFO]    DualShock (ID: 517)
[INFO]    Analog Controller (ID: 261)
[INFO]    Analog Joystick (ID: 773)
[INFO]    Guncon / G-Con 45 (ID: 260)
[INFO]    Justifier (ID: 516)
[INFO]    Mouse (ID: 258)
[INFO]    neGcon (ID: 1029)
[INFO]    (null) (ID: 0)
[INFO] Controller port: 8
[INFO]    PlayStation Controller (ID: 1)
[INFO]    DualShock (ID: 517)
[INFO]    Analog Controller (ID: 261)
[INFO]    Analog Joystick (ID: 773)
[INFO]    Guncon / G-Con 45 (ID: 260)
[INFO]    Justifier (ID: 516)
[INFO]    Mouse (ID: 258)
[INFO]    neGcon (ID: 1029)
[INFO]    (null) (ID: 0)
[INFO] Remaps: remap directory: D:\games\RetroArch\config\remaps
[INFO] Remaps: no game-specific remap found at D:\games\RetroArch\config\remaps\Beetle PSX HW\Crash_Bandicoot.rmp.
[INFO] Remaps: no core-specific remap found at D:\games\RetroArch\config\remaps\Beetle PSX HW\Beetle PSX HW.rmp.
[INFO] Redirecting save file to "D:\games\RetroArch\saves\Crash_Bandicoot.srm".
[INFO] Redirecting savestate to "D:\games\RetroArch\states\Crash_Bandicoot.state".
[INFO] Environ GET_LOG_INTERFACE.
[INFO] Environ SYSTEM_DIRECTORY: "D:\games\RetroArch\system".
[INFO] Environ SET_DISK_CONTROL_INTERFACE.
[INFO] Environ GET_PERF_INTERFACE.
[INFO] Environ PERFORMANCE_LEVEL: 15.
[INFO] Content loading skipped. Implementation will load it on its own.
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "Cross"
[INFO] 	RetroPad, User 1, Button "Y (left)" => "Square"
[INFO] 	RetroPad, User 1, Button "Select" => "Select"
[INFO] 	RetroPad, User 1, Button "Start" => "Start"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, User 1, Button "A (right)" => "Circle"
[INFO] 	RetroPad, User 1, Button "X (up)" => "Triangle"
[INFO] 	RetroPad, User 1, Button "L" => "L1"
[INFO] 	RetroPad, User 1, Button "R" => "R1"
[INFO] 	RetroPad, User 1, Button "L2" => "L2"
[INFO] 	RetroPad, User 1, Button "R2" => "R2"
[INFO] 	RetroPad, User 1, Button "L3" => "L3"
[INFO] 	RetroPad, User 1, Button "R3" => "R3"
[INFO] 	RetroPad, User 2, Button "B (bottom)" => "Cross"
[INFO] 	RetroPad, User 2, Button "Y (left)" => "Square"
[INFO] 	RetroPad, User 2, Button "Select" => "Select"
[INFO] 	RetroPad, User 2, Button "Start" => "Start"
[INFO] 	RetroPad, User 2, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, User 2, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, User 2, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, User 2, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, User 2, Button "A (right)" => "Circle"
[INFO] 	RetroPad, User 2, Button "X (up)" => "Triangle"
[INFO] 	RetroPad, User 2, Button "L" => "L1"
[INFO] 	RetroPad, User 2, Button "R" => "R1"
[INFO] 	RetroPad, User 2, Button "L2" => "L2"
[INFO] 	RetroPad, User 2, Button "R2" => "R2"
[INFO] 	RetroPad, User 2, Button "L3" => "L3"
[INFO] 	RetroPad, User 2, Button "R3" => "R3"
[INFO] 	RetroPad, User 3, Button "B (bottom)" => "Cross"
[INFO] 	RetroPad, User 3, Button "Y (left)" => "Square"
[INFO] 	RetroPad, User 3, Button "Select" => "Select"
[INFO] 	RetroPad, User 3, Button "Start" => "Start"
[INFO] 	RetroPad, User 3, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, User 3, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, User 3, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, User 3, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, User 3, Button "A (right)" => "Circle"
[INFO] 	RetroPad, User 3, Button "X (up)" => "Triangle"
[INFO] 	RetroPad, User 3, Button "L" => "L1"
[INFO] 	RetroPad, User 3, Button "R" => "R1"
[INFO] 	RetroPad, User 3, Button "L2" => "L2"
[INFO] 	RetroPad, User 3, Button "R2" => "R2"
[INFO] 	RetroPad, User 3, Button "L3" => "L3"
[INFO] 	RetroPad, User 3, Button "R3" => "R3"
[INFO] 	RetroPad, User 4, Button "B (bottom)" => "Cross"
[INFO] 	RetroPad, User 4, Button "Y (left)" => "Square"
[INFO] 	RetroPad, User 4, Button "Select" => "Select"
[INFO] 	RetroPad, User 4, Button "Start" => "Start"
[INFO] 	RetroPad, User 4, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, User 4, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, User 4, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, User 4, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, User 4, Button "A (right)" => "Circle"
[INFO] 	RetroPad, User 4, Button "X (up)" => "Triangle"
[INFO] 	RetroPad, User 4, Button "L" => "L1"
[INFO] 	RetroPad, User 4, Button "R" => "R1"
[INFO] 	RetroPad, User 4, Button "L2" => "L2"
[INFO] 	RetroPad, User 4, Button "R2" => "R2"
[INFO] 	RetroPad, User 4, Button "L3" => "L3"
[INFO] 	RetroPad, User 4, Button "R3" => "R3"
[INFO] 	RetroPad, User 5, Button "B (bottom)" => "Cross"
[INFO] 	RetroPad, User 5, Button "Y (left)" => "Square"
[INFO] 	RetroPad, User 5, Button "Select" => "Select"
[INFO] 	RetroPad, User 5, Button "Start" => "Start"
[INFO] 	RetroPad, User 5, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, User 5, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, User 5, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, User 5, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, User 5, Button "A (right)" => "Circle"
[INFO] 	RetroPad, User 5, Button "X (up)" => "Triangle"
[INFO] 	RetroPad, User 5, Button "L" => "L1"
[INFO] 	RetroPad, User 5, Button "R" => "R1"
[INFO] 	RetroPad, User 5, Button "L2" => "L2"
[INFO] 	RetroPad, User 5, Button "R2" => "R2"
[INFO] 	RetroPad, User 5, Button "L3" => "L3"
[INFO] 	RetroPad, User 5, Button "R3" => "R3"
[INFO] Environ GET_RUMBLE_INTERFACE.
[libretro INFO] Rumble interface supported!
[INFO] Environ SET_PIXEL_FORMAT: XRGB8888.
[INFO] Environ GET_VARIABLE beetle_psx_hw_cd_access_method:
[INFO] 	sync
[INFO] Environ GET_VARIABLE beetle_psx_hw_cpu_freq_scale:
[INFO] 	100% (native)
[INFO] Environ GET_VARIABLE beetle_psx_hw_gte_overclock:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_gpu_overclock:
[INFO] 	1x(native)
[INFO] Environ GET_VARIABLE beetle_psx_hw_skip_bios:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_widescreen_hack:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_enable_memcard1:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_analog_calibration:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_renderer:
[INFO] 	hardware
[INFO] Environ GET_VARIABLE beetle_psx_hw_dither_mode:
[INFO] 	1x(native)
[INFO] Environ GET_VARIABLE beetle_psx_hw_pgxp_mode:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_pgxp_vertex:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_pgxp_texture:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_analog_toggle:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_enable_multitap_port1:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_enable_multitap_port2:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_mouse_sensitivity:
[INFO] 	100%
[INFO] Environ GET_VARIABLE beetle_psx_hw_gun_cursor:
[INFO] 	Cross
[INFO] Environ GET_VARIABLE beetle_psx_hw_initial_scanline:
[INFO] 	0
[INFO] Environ GET_VARIABLE beetle_psx_hw_last_scanline:
[INFO] 	239
[INFO] Environ GET_VARIABLE beetle_psx_hw_initial_scanline_pal:
[INFO] 	0
[INFO] Environ GET_VARIABLE beetle_psx_hw_last_scanline_pal:
[INFO] 	287
[INFO] Environ GET_VARIABLE beetle_psx_hw_use_mednafen_memcard0_method:
[INFO] 	libretro
[INFO] Environ GET_VARIABLE beetle_psx_hw_shared_memory_cards:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_frame_duping:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_display_internal_fps:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_crop_overscan:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_image_offset:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_image_crop:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_cd_fastload:
[INFO] 	2x (native)
[libretro INFO] Loading D:\games\ROMS\PSX\Crash_Bandicoot.cue...
[libretro INFO] Checking if required firmware is present.
[libretro INFO] Firmware found: D:\games\RetroArch\system\scph5502.bin
[libretro INFO] Firmware SHA1: F6BC2D1F5EB6593DE7D089C425AC681D6FFFD3F0
[INFO] Environ GET_VARIABLE beetle_psx_hw_renderer:
[INFO] 	hardware
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting Vulkan context.
[INFO] Environ SET_PIXEL_FORMAT: XRGB8888.
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting core OpenGL context (3.3).
[INFO] [CHEEVOS]: system RAM: 0000000022F00D20 2097152
[INFO] [CHEEVOS]: save RAM:   0000000015E2A691 131072
[INFO] [CHEEVOS]: video RAM:  0000000000000000 0
[INFO] [CHEEVOS]: RTC:        0000000000000000 0
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] Environ GET_VARIABLE beetle_psx_hw_internal_resolution:
[INFO] 	4x
[INFO] Environ GET_VARIABLE beetle_psx_hw_display_vram:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_widescreen_hack:
[INFO] 	disabled
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Timings deviate too much. Will not adjust. (Display = 59.94 Hz, Game = 49.76 Hz)
[WARN] Cannot use CPU filters when hardware rendering is used.
[INFO] [Video]: Video @ 640x480
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [GL]: Found GL context: wgl
[INFO] [GL]: Detecting screen resolution 2560x1440.
[INFO] [WGL]: wglSwapInterval(1)
[INFO] [GL]: Vendor: ATI Technologies Inc., Renderer: AMD Radeon (TM) R9 390 Series.
[INFO] [GL]: Version: 3.3.13497 Core Profile Context 23.20.808.1792.
[INFO] [GL]: Using Core GL context, setting up VAO...
[INFO] [GL]: Using resolution 640x480
[INFO] [GL]: Default shader backend found: glsl.
[WARN] Rendering context is incompatible with shader type: nul
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[ERROR] [GL]: Failed to parse GLSL shader.
[ERROR] [GL]: Failed to initialize shader, falling back to stock.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 330.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 1 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Initializing HW render (4096 x 4096).
[INFO] [GL]: Max texture size: 16384 px, renderbuffer size: 16384 px.
[INFO] [GL]: Supports FBO (render-to-texture).
[INFO] [XInput]: Found XInput v1.4.
[INFO] [XInput]: Found controller, user #0
[INFO] [XInput]: Pads connected: 1
[INFO] [DINPUT]: Enumerating joypads ...
[INFO] [DINPUT]: Device #0 PID: {C21D} VID:{046D}
[INFO] [DINPUT]: Done enumerating joypads ...
[INFO] [XInput]: Attempting autoconf for "XInput Controller (User 1)", user #0
[INFO] [DINPUT]: Found XInput pad at index 0 (DINPUT index 0)
[INFO] [XInput]: Found VID/PID (046D/C21D) from DINPUT index 0 for "XInput Controller (User 1)", user #0
[INFO] [XInput]: Attempting autoconf for user #1
[INFO] [XInput]: Attempting autoconf for user #2
[INFO] [XInput]: Attempting autoconf for user #3
[INFO] [XInput]: Attempting autoconf for user #4
[INFO] [XInput]: Attempting autoconf for user #5
[INFO] [XInput]: Attempting autoconf for user #6
[INFO] [XInput]: Attempting autoconf for user #7
[INFO] [XInput]: Attempting autoconf for user #8
[INFO] [XInput]: Attempting autoconf for user #9
[INFO] [XInput]: Attempting autoconf for user #10
[INFO] [XInput]: Attempting autoconf for user #11
[INFO] [XInput]: Attempting autoconf for user #12
[INFO] [XInput]: Attempting autoconf for user #13
[INFO] [XInput]: Attempting autoconf for user #14
[INFO] [XInput]: Attempting autoconf for user #15
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [Autoconf]: 63 profiles found.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: win32
[libretro INFO] gl_context_reset called.
[INFO] Environ GET_VARIABLE beetle_psx_hw_internal_resolution:
[INFO] 	4x
[INFO] Environ GET_VARIABLE beetle_psx_hw_display_vram:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE beetle_psx_hw_filter:
[INFO] 	nearest
[INFO] Environ GET_VARIABLE beetle_psx_hw_depth:
[INFO] 	dithered 16bpp (native)
[INFO] Environ GET_VARIABLE beetle_psx_hw_dither_mode:
[INFO] 	1x(native)
[INFO] Environ GET_VARIABLE beetle_psx_hw_wireframe:
[INFO] 	disabled
[libretro INFO] Building OpenGL state (4x internal res., 16bpp)
[libretro INFO] Binding program for first time: 30
[libretro INFO] Unbinding program for first time: 30
[libretro INFO] Binding program for first time: 31
[libretro INFO] Unbinding program for first time: 31
[libretro INFO] Binding program for first time: 32
[libretro INFO] Unbinding program for first time: 32
[INFO] [autoconf]: selected configuration: D:\games\RetroArch\autoconfig\xinput\XInput_Controller_User_1.cfg
[INFO] XAudio2: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0000000000883880
[INFO] Connecting to port 517: DualShock (ID: 1).
[libretro INFO] Controller 1: DualShock
[INFO] Environ SET_MESSAGE: DualShock on port 1: Analog button toggle is DISABLED, sticks are ON
[libretro INFO] Controller 2: PlayStation Controller
[libretro INFO] Controller 3: PlayStation Controller
[libretro INFO] Controller 4: PlayStation Controller
[libretro INFO] Controller 5: PlayStation Controller
[libretro INFO] Controller 6: PlayStation Controller
[libretro INFO] Controller 7: PlayStation Controller
[libretro INFO] Controller 8: PlayStation Controller
[INFO] [GL]: VSync => on
[INFO] [WGL]: wglSwapInterval(1)
[INFO] Environ SET_MESSAGE: DualShock on port 1: Analog toggle is DISABLED, sticks are ON
[libretro INFO] Target framebuffer size: 1024x960
[INFO] Environ SET_GEOMETRY.
[libretro INFO] Target framebuffer size: 2560x956
[INFO] Environ SET_GEOMETRY.
[libretro INFO] Target framebuffer size: 2560x1912
[INFO] Environ SET_GEOMETRY.
[INFO] [Config]: Saved new config to "D:\games\RetroArch\retroarch.cfg".
[INFO] Saving RAM type #0 to "D:\games\RetroArch\saves\Crash_Bandicoot.srm".
[INFO] Saved successfully to "D:\games\RetroArch\saves\Crash_Bandicoot.srm".
[libretro INFO] gl_context_destroy called.
[libretro INFO] [Beetle PSX HW]: Samples / Frame: 851.71533
[libretro INFO] [Beetle PSX HW]: Estimated FPS: 51.77786
[INFO] Saved core options file to "D:\games\RetroArch\config\Beetle PSX HW\Crash_Bandicoot.opt"
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.

```

**Comment by rz5** [comment] 2018-07-07 19:45
Most probably a duplicate of #322

**Closed** 2018-08-13 02:12 UTC
Labels: duplicate
