### ISSUE TITLE
[Feature Request] FMV Internal Upscaling

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#567] opened 2019-11-17 21:37 UTC
With build b0d5562 the videos are not upscaled and stay on the native resolution.
However I would expect if the internal resolution is increased a nearest neighbour or bilinear upscaling for the videos will be applied as well.
The user can recognize the wrong resolution if he uses shaders. For example an aa shader.

**Comment by ggdrt** [comment] 2019-11-18 04:56
@Papermanzero Is this an issue that is newly introduced? If so, examples would be appreciated so that the issue can be diagnosed.

**Comment by Papermanzero** [comment] 2019-11-18 12:59
It is a n issue which exists since the introduction of increased resolution.

I will make some screenshots and explain the issue in more details later

**Comment by ggdrt** [comment] 2019-11-18 13:39
Okay, so this is a feature request for some sort of upscaling filter in the core then. 

FMVs are native resolution because they are pre-rendered content stored in the game itself rather than something that is rendered in real time. Internal resolution upscaling affects real time rendering, not FMVs. The way the FMVs are currently upscaled will on your frontend's video setting.

**Comment by ggdrt** [comment] 2019-11-18 13:43
Okay so if I am understanding correctly, this is a feature request for some sort of upscaling filter provided by the core for FMVs.

FMVs are outputted at native resolution and unaffected by the internal resolution setting because they are pre-rendered content stored in the game itself rather than rendered in real time.

**Comment by Papermanzero** [comment] 2019-11-18 14:13
Indeed. This is the request. Otherwise some shaders are not working correctly.

**Comment by Papermanzero** [comment] 2019-11-18 14:56
Here is an example:

with OpenGL renderer native resolution:
![Silent Hill-191118-154912](https://user-images.githubusercontent.com/10263536/69062876-cb559600-0a1b-11ea-850c-2e5874b97ef3.png)

With Vulkan renderer 4x resolution:
![Silent Hill-191118-154956](https://user-images.githubusercontent.com/10263536/69062914-df999300-0a1b-11ea-91ee-f034a53e1c81.png)

With Vulkan renderer 4x resolution and shaders:
![Silent Hill-191118-155030](https://user-images.githubusercontent.com/10263536/69062939-ea542800-0a1b-11ea-9aff-f9dc8b369117.png)

Shader Vulkan preset:
___________________________________________________
shaders = 3

shader0 = shaders_slang/denoisers/shaders/fast-bilateral-3d.slang
filter_linear0 = false
scale_type0 = source

shader1 = shaders_slang/anti-aliasing/shaders/aa-shader-4.0-level2/aa-shader-4.0-level2-pass1.slang
filter_linear1 = false
scale_type1 = source
scale1 = 2.0

shader2 = shaders_slang/anti-aliasing/shaders/aa-shader-4.0-level2/aa-shader-4.0-level2-pass2.slang
filter_linear2 = false
scale_type2 = source

parameters = "SIGMA_R;AAOFFSET;AAOFFSET2"

AAOFFSET = "1.20"
AAOFFSET2  = "1.60"
___________________________________________________

**Comment by ggdrt** [comment] 2019-11-19 04:26
I am not familiar with how shaders are applied by the frontend so this is something we will need hizzle's input on.

@hizzlekizzle Currently for FMVs, the Vulkan renderer hands the frontend a native resolution 240-height or 480-height framebuffer regardless of the internal upscale. If we wanted these shaders to be applied properly would it be sufficient to have the Vulkan renderer give the frontend a framebuffer at the upscaled resolution with the FMV scaled to those dimensions?

**Comment by hizzlekizzle** [comment] 2019-11-19 14:42
Yes, I think so. Just scale it up to size via NN. As long as it's the right number of pixels per texel, the detection algos should work.

**Comment by ggdrt** [comment] 2019-11-22 04:55
@Papermanzero Does this issue also show up with the GL and software renderers as well? 

Just trying to understand the scope of this problem.

**Comment by Papermanzero** [comment] 2019-11-22 23:48
Yes it does. Software renderer has no upscaling so the issue is not relevant there. GL renderer has the same issue because FMVs are not upscaled. The question is also how to upscale them. E.g bilinear or nearest.

**Comment by ggdrt** [comment] 2019-11-23 03:59
The software renderer should have an internal gpu resolution option, is that not showing up for you?

**Comment by Papermanzero** [comment] 2019-11-23 09:47
Ah ok. It shows up. I thought the software renderer is equal to mednafen standalone. :)
So I believed that the software renderer ignores the resolution. 
But after a small test it is the same result.

**Comment by nezumisama** [comment] 2019-11-23 21:56
I currently see three options to have smooth, higher-quality graphics, either:
* You let shaders handle the 240p output form the emulated GPU. Or just bilinear filtering instead of shaders.
* You use a combination of options in the core, like increased internal resolution, MSAA, texture filtering and other, but with nearest-neighbour interpolation (no shaders).
* Or you combine the two aforementioned approaches.

The first option always gives filtered image but there's a problem that the shaders are either designed to:
* Filter general images, but then they can't at the same time give an image, that doesn't have aliasing, preserves finer details and is free from artifacts from ringing.
* Upscale pixel-art images, which work great for low-color 2d graphics, but not so for general images.
The second option is great, but has one major flaw - the MDEC videos are pixelated.
The third option has the same problem with filtering as the first and also in the process of filtering, the crisper 3d graphics provided by increased internal resolution are blurred by the filter.

In general, the problem is that PSX games produce a combination of different types of graphics: textured 3d models, sprites, detailed backgrounds and videos (which are shown directly or sometimes treated as a background for 3d models like in Final Fantasy 8 for example). Each of these types of output needs special treatment. For 3d graphics we already have increased resolution, MSAA and texture filtering. If I'm not mistaken, Backgrounds are also affected by the texture filter from what I've observed. Which leaved MDEC videos.

Given the above, in my opinion, it would make sense to add MDEC Video filtering within the core. I don't know the code but perhaps the filters for textures could be re-used. Videos are a similar type of image to textures enough to support that idea.

**Comment by ggdrt** [comment] 2019-11-26 17:37
Issue is duplicate of #292. I won't close this one though since there's good information in here.

**Comment by Papermanzero** [comment] 2019-12-02 22:09
So I did a test with shaders. I dumped the native resolution and upscaled them with nearest neighbor to HD. After that I applied following shader preset:

shaders = 3

shader0 = shaders_slang/denoisers/shaders/fast-bilateral-3d.slang
filter_linear0 = false
scale_type0 = source

shader1 = shaders_slang/anti-aliasing/shaders/aa-shader-4.0-level2/aa-shader-4.0-level2-pass1.slang
filter_linear1 = false
scale_type1 = source
scale1 = 2.0

shader2 = shaders_slang/anti-aliasing/shaders/aa-shader-4.0-level2/aa-shader-4.0-level2-pass2.slang
filter_linear2 = false
scale_type2 = source

parameters = "SIGMA_R;AAOFFSET;AAOFFSET2"

AAOFFSET = "1.20"
AAOFFSET2  = "1.60"


HD Nearest Upscale:
![Silent Hill-191202-223723-191202-225845](https://user-images.githubusercontent.com/10263536/69999152-3e045c80-1558-11ea-97aa-f87645eb01b6.png)

HD Nearest Upscale + Shader:
![Silent Hill-191202-223723](https://user-images.githubusercontent.com/10263536/69999122-2fb64080-1558-11ea-8717-15fd90a38ef4.png)

HD Nearest Upscale:
![Silent Hill-191202-223726](https://user-images.githubusercontent.com/10263536/69999175-4ceb0f00-1558-11ea-98bc-189ee96f42d3.png)

HD Nearest Upscale + Shader:
![Silent Hill-191202-223726-191202-225929-191202-230111](https://user-images.githubusercontent.com/10263536/69999187-54aab380-1558-11ea-9802-5f2b84e5f322.png)

HD Nearest Upscale:
![Silent Hill-191202-223749](https://user-images.githubusercontent.com/10263536/69999206-60967580-1558-11ea-90a6-d9f4517f0d97.png)

HD Nearest Upscale + Shader:
![Silent Hill-191202-223749-191202-230050](https://user-images.githubusercontent.com/10263536/69999237-7441dc00-1558-11ea-88fe-a9abc3af3aff.png)


It becomes a little bit blurry. But as a conclusion. I would only implement a nearest upscaling for videos which is according to the resolution factor. The users can apply shaders on top of that.
Alternativly you implement a bilinear video filter option which is applied for MDEC videos.
But I would do that in a later point in time. First, just upscale the video in accordance with the resolution factor via nearest neighbor

**Comment by ggdrt** [comment] 2020-02-21 23:39
@Papermanzero If you're able to build cores, I've updated the Vulkan renderer on commit 66ff383 so that FMVs will now upscale to your selected Internal Resolution multiplier.

**Comment by Papermanzero** [comment] 2020-02-24 14:30
I tried to compile but I have an issue with 
mednafen/cdrom/CDAccess.cpp:
if(strlen(path) >= 4 && !strcasecmp(path + strlen(path) - 4, ".ccd"))

strcasecmp is not unknown.
Can u build a version?

**Comment by ggdrt** [comment] 2020-02-25 02:36
What platform are you building the core for?

**Comment by Papermanzero** [comment] 2020-02-25 14:01
Windows 10

**Comment by ggdrt** [comment] 2020-02-25 23:25
@Papermanzero Here's a Windows 10 x86_64 build of 957ee8c: [mednafen_psx_hw_libretro.zip](https://github.com/libretro/beetle-psx-libretro/files/4252616/mednafen_psx_hw_libretro.zip)

You could also acquire it via the Online Updater if you prefer now that the update has been merged into master branch, but the buildbot does not have the update yet as I'm writing this.

This build has the FMV upscaling update to Vulkan included. Just a fair warning that the GL renderer does not have the FMV upscaling changes.

**Comment by Papermanzero** [comment] 2020-02-26 00:43
Working perfectly. Thanks a lot. Tested Silent Hill, Soul Blade etc. all games with FMV looks pretty good.

**Comment by hizzlekizzle** [comment] 2020-02-26 04:55
Awesome. Thanks for confirming. I'll close this now.

**Comment by ggdrt** [comment] 2020-02-26 05:13
@hizzlekizzle I'm going to reopen this for the time being since the FMV internal upscaling is currently only implemented in the Vulkan renderer. The OpenGL and software renderers haven't received this feature yet. Sorry for any confusion.

**Comment by Papermanzero** [comment] 2020-03-08 23:52
Related to this one: https://github.com/libretro/beetle-psx-libretro/issues/245

**Comment by ggdrt** [comment] 2020-03-13 00:40
@Papermanzero Can you provide an example of the GL renderer FMV upscaling differing from the Vulkan renderer? Looking at the GL renderer code and doing GL frame captures I'm fairly certain the FMVs are already upscaled before being handed over to the frontend.

**Comment by Papermanzero** [comment] 2020-03-14 12:43
I will try it. Will do some screenies tomorrow

**Comment by Papermanzero** [comment] 2020-03-16 17:39
I dont even have to make screenshots. OpenGL behaves exactly the same as vulkan. So upscaling works for both now.

**Comment by ggdrt** [comment] 2020-03-16 20:19
Ok, thanks for confirming. So based on the previous discussion in this thread I think you said that the software renderer lacks this feature. Are your shaders not working properly at upscaled internal resolutions with the software renderer?

**Comment by Papermanzero** [comment] 2020-03-19 17:32
The vulkan renderer missed the feature. Tested the software renderer, which works as well. So i guess we can close the issue. But if u want to implement a bilinear filter beside the nearest neighbor.

**Comment by ggdrt** [comment] 2020-03-20 00:29
So prior to this issue thread, both the GL renderer and software renderers had internal upscaling on FMVs while the Vulkan renderer did not have it. That clears things up, thanks.

Giving a choice of upscaling filter is a possible improvement for the future.

**Closed by ggdrt** 2020-03-20 00:29 UTC

**Comment by joppuyo** [comment] 2021-12-04 13:50
What settings are you using?

I'm unable to use any filters/shaders on FMVs when my internal resolution is over 1x. I tried both Vulkan and OpenGL.

Running stable version of RetroArch (1.9.13) and Beetle PSX HW (0.9.44.1).

**Comment by Papermanzero** [comment] 2021-12-04 23:54
Standard Settings. Filters are working great.

**Comment by MishaTrent** [comment] 2022-06-08 15:05
> Ok, thanks for confirming. So based on the previous discussion in this thread I think you said that the software renderer lacks this feature. Are your shaders not working properly at upscaled internal resolutions with the software renderer?

Not to create a separate topic, I'll ask here. Do you plan to add anti-aliasing for FMV videos with more than 1x internal resolution in the future?
