### ISSUE TITLE
60 Hz - PAL Mode

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#503] opened 2019-05-12 15:51 UTC
Feature request to speed up PAL game to 60 Hz without increasing or changing the sound settings in retroarch itself. Many pal games suffer due to 50 Hz but habe a good translation. To get the best of two worlds it would be great if the emulator offers a feature to speed up games, without patching.

**Comment by Papermanzero** [comment] 2019-05-12 15:58
Some boot disc seems to offer a similar feature.
https://consolecopyworld.com/psx/psx_utils_bootcd.shtml

**Comment by hizzlekizzle** [comment] 2019-05-12 22:11
I've tried to implement this before but it's surprisingly hard. The 50/60 Hz stuff touches a lot of stuff fairly deep in the core, much more than I expected.

**Comment by trostboot** [comment] 2019-05-13 08:42
Duplicate of #67. As described there, methods that allow for this on real hardware don't work with either mednafen or beetle. And yes, that would be a great feature if it can be made to work.

**Comment by Papermanzero** [comment] 2019-05-13 13:50
> Duplicate of #67. As described there, methods that allow for this on real hardware don't work with either mednafen or beetle. And yes, that would be a great feature if it can be made to work.

But the video mode is different than the refresh rate. 
In general there are two "TV settings". 
The one is the "color transmission mode" which is different in each region. 
Therefore people used the term to define "Region Video mode".
Those are PAL, NTSC and SECAM. The standards define also the amount of lines 
In addition to the "color transmission", you have the "refresh rate" or "FPS".
Those can be 25Hz, 30Hz, 50Hz and 60Hz.

But in general you can combine both settings independently.
This is why PAL also defines a PAL60 Mode.
https://en.wikipedia.org/wiki/PAL#Multisystem_PAL_support_and_%22PAL_60%22

**Comment by trostboot** [comment] 2019-05-13 14:00
If you read the issue, it's clear people are also referring to refresh rates. No one really cares about the color components, because the request for that features mainly stems from the desire to run slowed down PAL games at their original speeds. Feel free to argue that the title of the original request should be amended, but both want the same feature.

**Comment by Papermanzero** [comment] 2019-05-13 14:16
I only want to emphasize that u need to differentiate between the two modes.
Because the color component (PAL, NTSC) also defines the amount of TV lines, which are used.
Some PAL Games have therefore more "visible screen" than NTSC games. 
This only needs to be clear, in case someone implements the feature.

**Closed** 2019-05-13 14:21 UTC
