### ISSUE TITLE
[Vulkan] bad render water in jumping flash 2.

### ISSUE THREAD

**Issue by darkxex** [libretro/beetle-psx-libretro#628] opened 2020-03-13 17:24 UTC
![image](https://user-images.githubusercontent.com/17991404/76644638-2a449b00-6536-11ea-9066-cb0672066766.png)
in Vulkan render, the water is bad rendered.
this is the first level of the game: jumping flash 2.

**Comment by rz5** [comment] 2020-03-13 17:48
Duplicate of #481

**Closed by rz5** 2020-03-13 17:48 UTC
