### ISSUE TITLE
[Feature Request] Add custom texture dumping/injection support to Beetle PSX Using OpenGL Renderer  

### ISSUE THREAD

**Issue by danprice142** [libretro/beetle-psx-libretro#798] opened 2021-06-03 23:53 UTC
Ability to dump textures from VRAM
Ability to replace textures with full-color, high-resolution images that the PSX cannot support natively
Should preferably support use of custom textures of any size. Must at least support injection of textures up to 4k resolution.
Support use of common image filetypes (such as PNG and JPG)
Support for loading texture packs Using OpenGL Renderer

**Comment by hizzlekizzle** [comment] 2021-06-04 00:11
This is a duplicate of https://github.com/libretro/beetle-psx-libretro/issues/492, which is already at least partially functioning.

**Closed** 2021-06-05 09:59 UTC
