### ISSUE TITLE
[OpenGL] Crash Bandicoot 3 Warped - Holes in the floor

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#355] opened 2018-06-24 20:06 UTC
Settings

Renderer: Hardware (OpenGL)
Software Framebuffer: Off
Adaptive Smoothing: Off
Internal GPU Resolution: 4x
Texture filtering: bilinear
Internal Color depth: 32bpp
Wireframe Mode: Off
Display Full VRAM: Off
PGXP operation mode: Memory only
PGXP vertex cache: On
PGXP perspective correct texturing: On
Widescreen mode hack: Off
Frame duping: Off
CPU Frequency Scaling: 100%
GTE Overclock: Off
GPU rasterizer overclock: 1x
Skip Bios: Off
Dithering pattern: 1x
Display interal FPS: Off
Initial scanline: 0
Last scanline: 239
Initial scanline PAL: 0
Last scanline PAL: 287
Crop Overscan: On
Additional Cropping: Off
Offset Cropped Image: Off
DualShock Analog button toggle: Off
Port 1 Multitap: Off
Port 2 Multitap: Off
Gun Cursoer: Cross
Mouse Sensitivity: 100%
CD Access Method: sync
Memcard 0 method: libretro
Enable memory card 1: on
Shared memcards: off
Increase cd loading speed: 2x

GPU: Nvidia 760 GTX

Description: Sometimes the floor has polygon holes (the polygon disappears and reappears).
However this could be also game related. Nevertheless I though this only occurs with far objects, not with near floors. This was the first time I recognized that the polygon was missing during the level select.

Screenshot:
![crash bandicoot 3 - warped-180624-211633](https://user-images.githubusercontent.com/10263536/41823142-d5e9b25e-77fa-11e8-9e6e-00cb7feb4716.png)

**Comment by Jj0YzL5nvJ** [comment] 2018-06-24 22:48
That is the normal behaviour even on real hardware.
https://imgur.com/a/C12MCkq

And can be reproduced in many other emulators, like PCSX-Reloaded, PCSXR-PGXP, ePSXe, XEBRA, etc.

More info:
http://youtu.be/U-vTy6ayv9E?t=3m30s
https://www.ngemu.com/threads/pcsxr-pgxp.186369/#post-2513177

http://youtu.be/S8aKUjfpwic
https://www.ngemu.com/threads/pcsxr-pgxp.186369/#post-2513673

http://youtu.be/WtDoOd0k-WY
https://www.ngemu.com/threads/pcsxr-pgxp.186369/page-2#post-2516385

https://www.ngemu.com/threads/pcsxr-pgxp.186369/page-2#post-2517201

**Comment by rz5** [comment] 2018-06-24 23:21
Alright, it's not a bug, so I'm closing it. @Papermanzero, I notice you're doing several bug reports. Given what happened in this thread, please ensure that you are not reporting the correct emulation as a bug.

**Closed by rz5** 2018-06-24 23:21 UTC

**Comment by Jj0YzL5nvJ** [comment] 2018-06-24 23:57
There are many "glitches" hidden in the poor resolution of the old TVs, N64 has many of them.
 It's difficult to verify many of these without the real hardware or a reliable "perfect pixel" emulator.
 I think it's good to document this kind of glitches, "if it's not done today, someone could do it tomorrow".
