### ISSUE TITLE
Japanese games cause retroarch to crash upon loading

### ISSUE THREAD

**Issue by meatbee** [libretro/beetle-psx-libretro#382] opened 2018-07-24 08:19 UTC
![capture](https://user-images.githubusercontent.com/39861306/43125587-64c7cc16-8f22-11e8-9813-6430650d0275.PNG)

I have all the right bios files (SCPH550-).

Loading a .cue file for any Japanese games causes retroarch to crash instantly.

**Comment by bparker06** [comment] 2018-07-24 12:13
Is this the hw or sw core? What's one of the games that you tried?

**Comment by ggdrt** [comment] 2020-02-26 07:04
I'm unable to reproduce this issue. The core and RetroArch have both been significantly updated since this issue was created; given this issue is almost two years old and no additional information was provided by the user, I'm going to close this.

**Closed by ggdrt** 2020-02-26 07:04 UTC
