### ISSUE TITLE
[AUDIO] No cd audio with Beetle PSX or Beetle PSX HW

### ISSUE THREAD

**Issue by YesterPlay80** [libretro/beetle-psx-libretro#486] opened 2019-02-05 22:42 UTC
## Description

No cd audio with Beetle PSX or Beetle PSX HW

### Actual behavior
 
No matter which game I start, no matter withc Beetle core I use, I can't get CD audio music to work. The CUE files are okay, the music is played using the PCSX Rearmed core, it's played in ePSXe, audio also plays just fine when opening the cues in Ultra ISO. 

For example, this is my cue file of "Ridge Racer", with working music in every other emulator:

```
FILE "RIDGERACERUSA.bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    INDEX 01 00:22:66
  TRACK 03 AUDIO
    INDEX 01 05:42:54
  TRACK 04 AUDIO
    INDEX 01 10:17:50
  TRACK 05 AUDIO
    INDEX 01 15:38:26
  TRACK 06 AUDIO
    INDEX 01 21:05:08
  TRACK 07 AUDIO
    INDEX 01 26:13:72
  TRACK 08 AUDIO
    INDEX 01 31:18:16
  TRACK 09 AUDIO
    INDEX 01 33:20:17
  TRACK 10 AUDIO
    INDEX 01 34:37:37
  TRACK 11 AUDIO
    INDEX 01 34:49:15
  TRACK 12 AUDIO
    INDEX 01 36:53:17
  TRACK 13 AUDIO
    INDEX 01 38:32:11
  TRACK 14 AUDIO
    INDEX 01 41:03:00
```

### Steps to reproduce the bug

I tried to load the games through Emulationstation, as well as directly through retroarch, the behaviour is always the same. I tried several games, which all work fine in other emulators.

### Version/Commit

RetroArch 1.7.6
Beetle PSX 0.9.44.1 5359198
Beetle PSX HW 0.9.44.1 5359198

### Core options

I left all core options as they were

### Environment information

- OS: Windows 10 x64 1803
- GPU: Nvidia GT650M with driver 417.35
- CPU: Intel Core i7-3630QM

**Comment by DukeJP** [comment] 2019-02-06 17:19
I dont have any problem here. Maybe a bad rip? I have this cue file:

> FILE "Ridge Racer (USA) (Track 01).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
FILE "Ridge Racer (USA) (Track 02).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ridge Racer (USA) (Track 03).bin" BINARY
  TRACK 03 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ridge Racer (USA) (Track 04).bin" BINARY
  TRACK 04 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ridge Racer (USA) (Track 05).bin" BINARY
  TRACK 05 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ridge Racer (USA) (Track 06).bin" BINARY
  TRACK 06 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ridge Racer (USA) (Track 07).bin" BINARY
  TRACK 07 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ridge Racer (USA) (Track 08).bin" BINARY
  TRACK 08 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ridge Racer (USA) (Track 09).bin" BINARY
  TRACK 09 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ridge Racer (USA) (Track 10).bin" BINARY
  TRACK 10 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ridge Racer (USA) (Track 11).bin" BINARY
  TRACK 11 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ridge Racer (USA) (Track 12).bin" BINARY
  TRACK 12 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ridge Racer (USA) (Track 13).bin" BINARY
  TRACK 13 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ridge Racer (USA) (Track 14).bin" BINARY
  TRACK 14 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00



i am using the redump format.

**Comment by YesterPlay80** [comment] 2019-02-07 14:36
I don't think the rip is bad, it works in every other emulator and even on the Playstation Classic console (which uses PCSX). As far as I know, by far not every emulator supports the ReDumpf format, that's why I prefer the classic CUE+BIN one, as it should work basically everywhere.

**Comment by rz5** [comment] 2019-02-08 04:32
@YesterPlay80
It's a "bad rip" in the sense that your cue sheet is missing pregap information or it's a non-standard cue sheet, things that beetle-psx - and by extension, Mednafen - expects.

PCSX and ePSXe may be more convenient to use in that both emulators have hacks to handle special cases which are not specified in the CDRWIN Users Manual (the document where the cue sheet format is specified).
But you know, hacks are hacks, I believe the intent behind Mednafen as a project is to avoid those. So it's not a bug to not have a hack to support non-standard cue sheets or even missing info. 

If you want to know the motives behind this design or a more technical explanation on the matter, try to reach out to Rhypheca over at the Mednafen forums/IRC. If you want this core to have the hacks that ePSXe/PCSX has, consider adding the code yourself.
Or rephrase this bug report as a feature request and optionally add a bounty.

Please do test if this is also happening on Mednafen upstream. If Mednafen can play audio with your dump and this core cannot, then it's a valid bug from the point of view of this core.
I'll close this since DukeJP's dump works and yours does not. Feel free to reopen it if you confirm it's a valid bug.

**Closed by rz5** 2019-02-08 04:32 UTC

**Comment by EugenM88** [comment] 2020-03-06 01:36
Hello, the beetle psx hw is not able to play any background music from The Adventures of Lomax, using epsxe with epsxe spu core 1.8.0 works just fine, is there a possibility to fix this bug please?

**Comment by maxlefou** [comment] 2022-01-05 19:04
For info, bin tracks are usually just wav files. If you change the extension to wav, it will work right away. Maybe if the core treats those files like wav tracks?
