### ISSUE TITLE
[OpenGL/Upscaled Software] RE2 - Dual Shock Ver. - Vertical white lines on fire effect

### ISSUE THREAD

**Issue by cheds89** [libretro/beetle-psx-libretro#406] opened 2018-08-12 13:36 UTC
Hi everyone,

I'm using RetroArch 1.7.3, with the latest Beetle PSX core (Software). I'm experiencing the following visual bug on the moving flame alpha textures at the very beginning of Resident Evil 2 - Dual Shock Version. Here are some pictures - 

https://imgur.com/a/AjPGKzL

These white lines are definitely way more noticeable in motion and tend to flicker as the flame effect moves. The GPU internal resolution is set at 4x. The lines are less noticeable at 2x and completely absent at 1x (Native). I've tried other video drivers and the same issue persists.

EDIT - Noticed the same issue occurs at 4x GPU Internal Resolution on Beetle PSX HW core with D3D11 Driver. 

Any help would be appreciated. I hope I have provided enough information. If not, please ask.

Thanks!

**Comment by DukeJP** [comment] 2018-08-13 14:54
I can confirm this problem, in Vulkan with upscaled resolution in  4abdf04.  
![resident evil 2 - dual shock-180813-114655](https://user-images.githubusercontent.com/24689994/44039311-3679f1ae-9eef-11e8-9610-1cd7a71f323a.png)

This not happens in previous versions, or resolution set to 1x

**Comment by hizzlekizzle** [comment] 2018-08-13 15:39
@DukeJP That could definitely be related to the bilinear filtering. Can you see if it resolves when the texture filtering is set to nearest, xBR or SABR? (you have to 'close content' and then reopen the game for the filtering changes to take effect; a simple 'restart' won't cut it)

**Comment by DukeJP** [comment] 2018-08-13 16:14
I dont know that!!!! (about re-open game to take effect). 
Well, with "nearest" the "slicing" is gone. But i notice a very little "motion blur" in Leon and zombies, insignificant for me.
Thanks for the tip.

**Comment by cheds89** [comment] 2018-08-14 07:49
I think your issue was in the Beetle HW core, correct DukeJP? The white lines I'm experiencing are in the Beetle Non-HW core (Software) exclusively and only at 2x or 4x GPU internal resolution.

In that core there's no texture filtering options as far as I can see Hizzlekizzle.

Here's another picture - 

![re2-3](https://user-images.githubusercontent.com/42318042/44078493-f68fadf8-9fe9-11e8-9fde-69d54831c6c8.png)

The lines move and flicker along with the alpha flame effect. 

Thanks!

**Comment by hizzlekizzle** [comment] 2018-08-14 15:56
Yeah, no filtering in the non-HW version. I think that's the same underlying issue as the green outlines in FF7, which I don't think anyone has an answer for.

**Comment by cheds89** [comment] 2018-08-15 07:48
Alright thanks for the reply. I'll leave this issue open.

**Comment by twinaphex** [comment] 2018-11-30 16:42
A PR just got merged which is supposed to fix this. Can the original poster please try this game again with an updated core?

**Comment by orbea** [comment] 2018-12-04 20:59
@cheds89 Can you please test this?

**Comment by wesker265** [comment] 2019-01-06 09:42
I am seeing something similar to what @cheds89 is experiencing in the latest Retroarch 1.7.5 and latest Beetle PSX HW Core [0.9.44.1/1d6ba98]. I am seeing what looks like white or light-colored "crosshairs" in flames and weapon muzzle flashes when PGXP is set to "Memory+CPU"

![resident evil 2 dual shock mem cpu on](https://user-images.githubusercontent.com/45540160/50734414-1e07c580-115c-11e9-9891-d02d4fcb474f.png)

Here is a screenshot with PGXP set to "Memory Only":

![resident evil 2 dual shock mem only on](https://user-images.githubusercontent.com/45540160/50734434-64f5bb00-115c-11e9-8876-4d37cd57aa77.png)

I have been unable to produce a screenshot of the muzzle flashes but I can confirm that similar "crosshairs" appear when PGXP is set to "Memory + CPU". Setting PGXP to OFF or Memory Only fixes this.

@cheds89 can you please test and confirm if changing this setting fixes your issue?

**Comment by cheds89** [comment] 2019-01-07 07:50
@twinaphex @orbea @wesker265 

I will test on my end and let you all know ASAP. Just saw this sitting in my e-mails, sorry for the late reply.

Thanks

**Comment by cheds89** [comment] 2019-01-07 11:24
@twinaphex @orbea -- Testing is done.

This is what it originally looked like on Retroarch1.7.3 - Beetle PSX Software 0.9.44.1 4abdf04 (OpenGL): https://imgur.com/a/niQjqJP

And now on the latest releases - Retroarch 1.7.5 - Beetle PSX Software 0.9.44.1 c20eac9 (OpenGL): https://imgur.com/a/LEbBy3J

Looks like it's fixed! Great stuff, thanks 👍 

@wesker265 

I was able to replicate your issues exactly as you described. I used the latest Retroarch 1.7.5 - Beetle PSX HW 0.9.44.1 c20eac9 (Vulkan) with 4x GPU resolution.

This is with PGXP - Memory+CPU: https://imgur.com/a/1Uyi4LX

You can see those crosshairs in the muzzle flash + flames very clearly.

And this is with PGXP - Memory only which appears to fix the issue: https://imgur.com/a/Zb7tLiA. 

Hope this is helpful. Let us know if we need anything else.

Thanks.

**Comment by rz5** [comment] 2019-01-07 11:43
Thanks @cheds89 for testing it.
So the bug reported in this thread is seemingly fixed by iCatButler's commit (https://github.com/libretro/beetle-psx-libretro/commit/616a56355df1751983d17cb07adc37818f1ef93e).

As for the PGXP "memory + cpu" mode related bug, @wesker265 already made a bug report about it (#453).

I'm closing the issue.

**Closed by rz5** 2019-01-07 11:43 UTC
