### ISSUE TITLE
(Any Render) Black Screen | AMD RX 480

### ISSUE THREAD

**Issue by Traace** [libretro/beetle-psx-libretro#212] opened 2017-07-31 11:55 UTC
System OS: Windows 10 x64 (Build: 15064.483)
MB: Asus PRIME B350-PLUS
CPU: AMD Ryzen
GPU: AMD RX 480
RAM: 16GB DDR4@2666 CL14
Screens: 4x 1080p

What does happen:
When we start content with Mednafen PSX or Mednafen PSX HW we just get a black screen with both, GL and also vulkan. We have the proper Bios in place and double checked the MD5.
The Iso's and Cue's in our collection are redump verified too. makes sure nothing is corrupt there.

What is expected:
A proper mednafen psx core bootup with screen display.

Logs:
[log.txt](https://github.com/libretro/beetle-psx-libretro/files/1187442/log.txt)

Thanks :)

**Comment by bparker06** [comment] 2017-07-31 13:53
Duplicate of #188, this seems to be a Polaris chipset issue.

**Closed by bparker06** 2017-07-31 13:53 UTC
Labels: duplicate
