### ISSUE TITLE
Heat effect in F1 2000 broken 

### ISSUE THREAD

**Issue by CromlechDE** [libretro/beetle-psx-libretro#165] opened 2017-03-06 09:11 UTC
The heat effect at the Start of the Race in F1 2000 is not rendered correctly.

**Comment by DukeJP** [comment] 2017-03-09 18:56
how is the "correct" mode?

**Comment by Oggom** [comment] 2017-03-09 18:59
This is caused by the lack of GPU cache emulation https://github.com/libretro/beetle-psx-libretro/issues/12

**Comment by OptimalJew** [comment] 2017-10-09 00:48
Definitely fixed now. The effect matches both this (captured off a PS1) https://youtu.be/pwnVduGiT6Y?t=1m32s and standalone.

https://my.mixtape.moe/fxqnfj.webm

**Comment by rz5** [comment] 2017-10-09 01:24
yup, fixed in simias's ed0a329572695b5fa796ebdbdcc67e6d17e1765a commit.

**Closed by rz5** 2017-10-09 01:24 UTC
