### ISSUE TITLE
Metal Gear Solid - Texture corruption using Vulkan

### ISSUE THREAD

**Issue by knerlington** [libretro/beetle-psx-libretro#529] opened 2019-08-17 08:03 UTC
## Description

[Description of the bug]
Using more than x1 native GPU resolution with hardware rendering the textures get corrupted as soon as you open the weapon or item wheel using L2, R2. Before opening the inv. or weapon wheel it's perfect.

### Steps to reproduce the bug

1. Open the inventory or weapon wheel.

### Version/Commit
- RetroArch: 1.7.7
- Beetle PSX: 3e3acfc

### Core options
Tried every possible combination and it seems to be caused by the internal resolution scaling not working properly with Vulkan.

### Environment information

- OS: Windows 10
- GPU: RTX 2080 431.60

**Comment by backgamon** [comment] 2019-08-17 08:59
Same issue of https://github.com/libretro/beetle-psx-libretro/issues/524#issue-470289549

**Comment by rz5** [comment] 2019-12-19 09:34
Duplicate of #476

**Closed by rz5** 2019-12-19 09:34 UTC
Labels: duplicate
