### ISSUE TITLE
Multidisk PBP and savestates [$25]

### ISSUE THREAD

**Issue by Kierek** [libretro/beetle-psx-libretro#184] opened 2017-04-15 13:43 UTC
There is a weird behaviour regarding multidisk pbp and savestates. While in the middle of playing Parasite Eve I've been asked to change the disk. No problem, a couple of hotkeys later I'm playing again. 

The problem came out later, when I tried to load savestate made after disk change. It just doesn't work. Whenever I try to change location, it's unable to load it. I deducted that retroarch is still pointing to disk 1 and so I tried to change it. Nope, it looks like after loading savestate retroarch is losing count of available disk's and there's just "null" displayed. Using Disk Image Append didn't help either, I could choose disk index then, but I'm still experiencing the first problem.

Trying to change the disk to 2 before loading savestate doesn't help either. It seems that the only way for me to finish the game is by not using savestates. It's not a big problem for Parasite Eve, but I wanted to play some jrpgs after this and I just can't imagine doing it without savestates.

https://cloud.githubusercontent.com/assets/4080084/25064034/3a23e36c-21f2-11e7-894a-96e085e99d85.png

After a little bit of research it seems that the "null" problem happens only when saved on a disk different than the first one.

**Comment by Kierek** [comment] 2017-04-15 16:13
It works fine with several pbps and m3u file. After loading savestate from another disk it automatically changes retroarch's disk to said one and it works perfectly.

It's not a solution but at least a workaround.

**Comment by daninthemix** [comment] 2017-05-04 05:48
I was unable to replicate this problem on Resident Evil 2. It's an easy one to test as you can just switch to Disc 2 and begin a new game, which I did. I was able to relaunch Retroarch, run RE2 and load state immediately.

So either this is a problem with Parasite Eve, or a problem with your setup.

**Comment by daninthemix** [comment] 2017-05-05 10:20
I've added a bounty to this issue: https://www.bountysource.com/issues/44171556-multidisk-pbp-and-savestates

**Comment by Kierek** [comment] 2017-05-05 10:52
Thanks for confirming, I was worried that it was because of some corruption in my collection.

**Comment by rz5** [comment] 2017-11-21 07:51
@Kierek, @daninthemix,

A commit by @justinweiss was just merged and it purports to fix this bug. Please build it from source or use RA's core updater, double check if the core version ends with ae2f91f and check if it works.

**Comment by ofry** [comment] 2017-11-22 01:49
Please give me list of PS1 games which use more than 1 discs. Maybe I can try to test it.

**Comment by daninthemix** [comment] 2017-11-22 05:15
easiest one would be Resident Evil 2, as you can start on disk 2 immediately.

**Comment by ofry** [comment] 2017-11-23 20:26
I tried to convert Resident Evil 2 USA version (Redump)

1. Converted both discs from cue+multi-bin to cue+single bin. (via CDMage 1.02.1)
2. Converted both discs to pbp. 1 disc = 1 pbp. (PopStation)
3. Made ONE pbp from two PBP's. (PSX2PSP 1.4.2)

And disc change DOESN'T work at all. Disc Index = 1 all the time. If I press Right or Left, it stays 1.

I can give this files via Skype or P2P, etc.
My skype is ofryaka

**Comment by justinweiss** [comment] 2017-11-24 02:17
I think you can only change discs if the tray is open -- otherwise, left and right have no effect.

**Comment by ofry** [comment] 2017-11-24 02:43
@justinweiss Thank you.

I tried make savestate 0 on disc 1 and savestate 1 on disc 2. (start of the game, after cutscenes)

Then I reset the game and trying to switch between these states. First time it works, but eventually (2nd-3rd-4th...) time the game freezes.

**Comment by justinweiss** [comment] 2017-12-12 03:58
Hm, that's strange -- I just finished a playthrough of FFVII as a PBP with save states, and didn't run into any trouble after this fix. Unfortunately, the rest of my games are CHD, so I don't have much else to test with.

**Comment by ofry** [comment] 2017-12-13 13:41
Please contact me via Skype: ofryaka
or e-mail tim4job@bmail.ru

**Comment by ofry** [comment] 2018-01-09 02:04
And one more test case:

try to do "fake" PBP with 2 different games as 2-disk game.

Then, start game 1, make an quicksave, reset.
Switch to disk 2 of PBP, make an quicksave in another slot, reset.

"Pass test" = you can switch between these save states many times without crashes, glitches, etc.

**Comment by ofry** [comment] 2018-01-09 02:06
If it crashes or glitches, then it's a bug. Because save states should include (by default) all state info, SRAM (memory cards) too.

**Comment by remyabel** [comment] 2018-01-13 08:24
@ofry For Resident Evil 2, cannot reproduce. I'm using SLUS00748 and SLUS00756 (Leon and Claire discs respectively). If you are using a valid dump, each disc should come with two tracks. Steps:

1. Convert SLUS00748 2 *.bins to PBP
2. Convert SLUS00756 2 *.bins to PBP
3. Convert both PBP's to one PBP

I then followed your instructions. Save state once you gain control of Leon, change disc status, change disc index, restart, change save state index, save state for Claire. Restart, then switch save states.

The behavior I get is an message saying "Virtual CD Tray Drive Closed" and the Disc Index changes when you change states, but no soft-lock.

**Comment by ofry** [comment] 2018-01-13 08:34
After first switching save states, switch it again... and again... in 2-4 times you will get softlock.

**Comment by remyabel** [comment] 2018-01-13 08:43
Yes, I did switch multiple times but no soft-lock. Any other information you can provide? i.e, is the Disc Index "null" when it soft-locks?

**Comment by ofry** [comment] 2018-01-13 08:59
OK. I deleted these save states manually and make same states again.

Problem has gone now.

So this issue can be closed.

**Comment by ofry** [comment] 2018-01-14 17:07
@daninthemix Issue has solved. Please close this issue to release the bounty.

**Comment by daninthemix** [comment] 2018-01-14 17:13
I didn't open the issue so I can't close it. If someone claims the bounty (on bounty source) I will release it.

**Comment by ofry** [comment] 2018-01-14 17:26
@Kierek Please close this isssue to release the bounty or you should find bug in current implementation.

**Comment by ofry** [comment] 2018-01-17 19:08
Please reopen this issue.

Reason: https://github.com/libretro/beetle-psx-libretro/issues/297

**Comment by retro-wertz** [comment] 2018-01-18 21:21
i confirm @ofry diagnosis. this commit has broken PBP states. as describe in #297

**Comment by twinaphex** [comment] 2018-05-04 03:06
Hi there @daninthemix , the issue appears to be resolved yet the bounty money still is unclaimed by anybody.

What would  you like to have happen with this money? Would you like it to go to us and we send it to a bounty of your choosing or a new one? Or can we still expect somebody to claim it? I leave you in the driver's seat here.

**Comment by daninthemix** [comment] 2018-05-04 05:54
@twinaphex Yeah you can have the bounty.

**Comment by twinaphex** [comment] 2018-07-01 01:55
OK, closing then.

**Closed by twinaphex** 2018-07-01 01:55 UTC
Labels: bounty
