### ISSUE TITLE
[OpenGL/Vulkan] 3Xtreme - Flickering garbled texture line at bottom of screen and a small line on the loading title screen

### ISSUE THREAD

**Issue by saftle** [libretro/beetle-psx-libretro#393] opened 2018-07-26 19:53 UTC
This was initially reported by me here: https://github.com/libretro/beetle-psx-libretro/issues/43#issuecomment-223145717. These problems are both reproducible on the Vulkan and GL renderers. The software renderer does not have either problem. This was tested on commit: 581a08fc62a21515e4f9d9fb2d0e96e5da434f43

**During Gameplay:**

GL/Vulkan:
https://cloud.githubusercontent.com/assets/852777/15727972/06d19a82-285a-11e6-935f-8818d2f1f049.png

**Title Screen:**

GL/Vulkan:
https://user-images.githubusercontent.com/852777/43285188-76800970-911e-11e8-9cbb-a4d1fd03e53c.png

Software:
https://user-images.githubusercontent.com/852777/43285155-5e1e5c24-911e-11e8-8bbe-44615bceb040.png

**Comment by ggdrt** [comment] 2019-11-26 17:18
I'm going to close this since this seems to be a display issue rather than an actual rendering issue. The difference in coloration depends on when the opening FMV is skipped and is reproducible with upstream Mednafen. This texture exists in the overscan region, which is typically hidden by borders on older televisions. The initial/last scanline options exist to simulate this and have recently been implemented in both the GL and Vulkan renderers.

**Closed by ggdrt** 2019-11-26 17:18 UTC
Labels: bug, graphics bugs, opengl, vulkan

**Comment by ggdrt** [comment] 2019-11-26 17:21
Closing this since this seems to be a display issue rather than an actual rendering issue. The difference in coloration for the title screen depends on when the opening FMV is skipped and is reproducible with upstream Mednafen. 

Both examples of the strange coloration only exist in the overscan region, which is typically hidden by borders on older televisions. The initial/last scanline options exist to simulate this cropping and have recently been implemented in both the GL and Vulkan renderers.

**Comment by ggdrt** [comment] 2019-11-26 17:23
I'm going to close this since this seems to be a display issue representing accurate behavior rather than a rendering issue. The difference in coloration for the title screen depends on when the opening FMV is skipped and is reproducible with upstream Mednafen. 

Both examples of the strange coloration only exist in the overscan region, which is typically hidden by borders on older televisions. The initial/last scanline options exist to simulate this cropping and have recently been implemented in both the GL and Vulkan renderers.
