### ISSUE TITLE
Crash Bandicoot: Warped Corrupted textures on Vulkan

### ISSUE THREAD

**Issue by backgamon** [libretro/beetle-psx-libretro#524] opened 2019-07-19 12:01 UTC
## Description
When using scaling more of 1x i have heavy textures corruptions under Vulkan render.

[Description of the bug]
Many textures are corrupted.
### Expected behavior

[What you expected to happen]
https://image.noelshack.com/fichiers/2019/29/5/1563537179-screenshot-19-07-2019-13-51-33.jpg
https://image.noelshack.com/fichiers/2019/29/5/1563537183-screenshot-19-07-2019-13-52-07.jpg

### Actual behavior
https://image.noelshack.com/fichiers/2019/29/5/1563537225-screenshot-19-07-2019-13-48-09.jpg
https://image.noelshack.com/fichiers/2019/29/5/1563537225-screenshot-19-07-2019-13-48-43.jpg

### Steps to reproduce the bug

Just use scaling superior at 1x

### Version/Commit
RetroArch 1.7.7

- Beetle PSX: 0.9.44.1 3a3e397

### Core options
Renderer: Hardware
Software Framebuffer: On
Adaptive Smoothing: On
MDEC YUV Chroma Filter: On
Internal GPU Resolution: (1x Work) - Above -> Corruptions
MSAA: x16
Texture Filtering: XBR
Perspective Correction: On
PGXP Operation Mode: Memory Only

### Environment information

- OS: Windows 10 (1809) Pro X64
- Compiler: [In case you are running local builds]
- GPU: Gigabyte RTX 2070 OC (Up To Date)

**Comment by medievil1** [comment] 2019-07-19 22:07
it is fine for me 
GTX 1660
differences, I have msaa off  Text filtering to bilinear (one of those likely the culprit) same version of beetle 
![Untitled](https://user-images.githubusercontent.com/38597905/61568112-f7eaa880-aa4f-11e9-8d22-3d789d32b926.png)
I WILL note that the last few releases are sloooow compared to older ones... used to be easily  used at 16x internal, now even 8x is stuttering

**Comment by backgamon** [comment] 2019-07-20 08:12
No luck, without MSAA(and bilinear) same problem.
I have no problem with 8x (270 RTX/8700K 4.7Ghz)
But i guess it's from gestion of vulkan with RTX :/

**Comment by medievil1** [comment] 2019-07-20 14:57
actually after I posted that, I updated RA nightly and bam.. getting the same corruption now...
My internet went out(issues for the last week) and just now getting here to post it...

**Comment by backgamon** [comment] 2019-07-20 19:21
The only solution i found:
Using 3 point filter with OpenGL render - With XBR it cause small GFX issues too:
- OGL x8 + MSAA x16 + 3 Points filter -
http://emuscreenhd.free.fr/playstation/C/crash%20bandicoot%203/2.jpg

**Comment by Illynir** [comment] 2019-08-27 02:26
Same problem with my RTX 2060, GL is fine, Vulkan not.

Also on Xenogears/Dracula X (and probably many games).

**Comment by brianblakely** [comment] 2019-09-08 02:08
Duplicate of #476

**Comment by medievil1** [comment] 2019-12-01 19:45
probably related to above issue (476) but it is not limited to just 16x 
8x
![image](https://user-images.githubusercontent.com/38597905/69919246-eb884a80-1448-11ea-9c22-f4a4d3b8bc39.png)
4x
![image](https://user-images.githubusercontent.com/38597905/69919259-03f86500-1449-11ea-970a-13e913aa55e4.png)
I do think it MAY be related to the filter code though, cause for a brief second when the image comes up, textures are normal, then they corrupt

**Comment by brianblakely** [comment] 2019-12-01 21:15
It is unrelated to texture filtering, or at least disabling/enabling texture filtering doesn’t mitigate the issue.

**Comment by medievil1** [comment] 2019-12-02 03:13
I thought maybe it was still tied to the function(even if it doesn't go through the whole;e process)...just because of behavior...

**Comment by brianblakely** [comment] 2019-12-02 21:44
That is a valid point!

**Comment by rz5** [comment] 2019-12-19 09:34
Duplicate of #476

**Closed by rz5** 2019-12-19 09:34 UTC
Labels: duplicate, vulkan

**Comment by Illynir** [comment] 2019-12-19 14:18
It's fixed for me too, amazing work, guys. Thanks. :)
