### ISSUE TITLE
Keyboard buttons for analog axes don't work when remapped (via .rmp)

### ISSUE THREAD

**Issue by akumenon** [libretro/beetle-psx-libretro#880] opened 2023-04-11 18:53 UTC
## Description

If I change the controls of either the left or right analog sticks (via core controls, i.e. .rmp) the keyboard controls for them stop working.

### Expected behavior

Keyboard controls mapped to analog axes continue to work as usual.

### Actual behavior

Keyboard buttons mapped to the analog sticks stop working. Gamepads contine to work as expected.

### Steps to reproduce the bug

1. Run a game via Beetle PSX (HW in my case) that uses analog controls (like dualshock supported games)
2. Confirm that all keyboard controls work.
3. Open the Retroarch overlay->Controls->Port 1
4. Device type to dualshock
5. Change any left analog and/or right analog mappings.
6. Check if the controls you cnaged work in-game. (They don't, in my experience)

### Bisect results

There are some interesting things that happen when you change an analog control's mapping. Among them, it seems it's counterpart control (- to +, + to -) stops working too, e.g. if I change the left analog Y- control, besides left analog Y- not working on keyboard, left analog Y+ stops working on both gamepad and keyboard! So there's definitely some issue underlying the bug I'm reporting.

### Version/Commit

- Beetle PSX **HW**: 0.9.44.1/6ed5790

### Core options

Nothing out of the ordinary, But [here's my opt file](https://github.com/libretro/beetle-psx-libretro/files/11203869/Beetle.PSX.HW.opt.zip) just in case.

### Environment information

- Frontend: Retroarch (Steam) 1.15.0
- OS: Windows 10 Pro (x64) 22H2
- GPU: Nvidia GeForce GTX 970

**Comment by bslenul** [comment] 2023-04-13 09:45
Seems to be a RetroArch issue, I was able to reproduce with Flycast, Citra and Mupen64Plus-Next cores. Do you mind closing this issue and reposting it in https://github.com/libretro/RetroArch/issues instead?

**Closed as not planned** 2023-04-13 17:51 UTC
