### ISSUE TITLE
Weird texture bug in right corner HW - Resident Evil 1 Directors Cut 

### ISSUE THREAD

**Issue by IceLancerSR** [libretro/beetle-psx-libretro#287] opened 2017-12-23 22:17 UTC
Weird texture bug in right corner HW - Resident Evil 1 Directors Cut
I do not use any overlay /bezel Only Lottes which curves the screen a bit. Then this appears
https://i.imgur.com/kuwlDlrl.jpg

If i change shader in game it disappears untill next retroarch restart.
I am not sure what is it. But it only appears on HW version of core
It stays there entire game.
Win10x64
Ati rx470

Similar thing is happening with geom but to much less extent , only shows one line of weird colors around corner,barely visible 
https://i.imgur.com/xrNT1Zal.jpg

**Comment by Jj0YzL5nvJ** [comment] 2017-12-24 01:07
That "weird texture" is in reality part of the PS logo.

**Comment by IceLancerSR** [comment] 2017-12-24 05:08
PS Logo?Coming from where? From game it self? Because i cleaned retroarch from all image files because i tought of same thing.

**Comment by saftle** [comment] 2018-01-05 01:50
HW with the GL or Vulkan renderer? What are both the renderer in the quick menu and retroarch's driver set to?

**Comment by IceLancerSR** [comment] 2018-01-05 02:52
Both are Vulkan. I tried every possible option that image is visible even without curving screen. Its very distracting

**Comment by saftle** [comment] 2018-01-05 21:51
Is that the only game it occurs on?

**Comment by IceLancerSR** [comment] 2018-01-06 00:15
Can't tell , dont have big ps1 game database.

**Comment by ggdrt** [comment] 2020-02-26 05:02
Closing as a potential duplicate of #619 which has been solved.

**Closed by ggdrt** 2020-02-26 05:02 UTC
