### ISSUE TITLE
Weird missing textures

### ISSUE THREAD

**Issue by razorache** [libretro/beetle-psx-libretro#173] opened 2017-03-28 04:18 UTC
![007 - the world is not enough-170328-000208](https://cloud.githubusercontent.com/assets/19499190/24388892/9ec275e6-134b-11e7-906a-567a43c769c1.png)
![007 - the world is not enough-170328-000353](https://cloud.githubusercontent.com/assets/19499190/24388895/a1e91586-134b-11e7-8da1-1b7d5bd7a85b.png)
![007 - the world is not enough-170327-235806](https://cloud.githubusercontent.com/assets/19499190/24388898/a5bd2774-134b-11e7-9736-fd84b0a90e51.png)
![007 - the world is not enough-170327-235811](https://cloud.githubusercontent.com/assets/19499190/24388901/a96a1af8-134b-11e7-83f8-d2677dbc11d7.png)

I reinstalled my OS and everything (and I mean everything) and Installing directX seemed to cause it. The only way I can get it to work is to do a system restore. Any Ideas? I Need Directx for my front end

**Comment by cudencuden** [comment] 2017-03-28 04:24
i think issue is with the the new texture filtering BRZ and higher...but using ANY texture filtering is problematic now. i reverted back to http://buildbot.libretro.com/nightly/linux/x86_64/2017-03-25_cores/ and is okay.

**Comment by razorache** [comment] 2017-03-28 04:59
I made some progress, It only does it when hard GPU sync is disabled.

**Comment by cudencuden** [comment] 2017-03-28 05:41
@razorache , i enabled GPU sync just now..seems to fix issue

**Comment by DukeJP** [comment] 2017-03-30 20:15
What render settings you have? Make sure you have the same render setting in Retroarch (general options) and the core options too. I have a similar problem: I have Vulkan in the general settings and OpenGL in the core settings, and i have missing textures too. When i changed the core options to Vulkan the problem fixed.

**Comment by twinaphex** [comment] 2017-03-31 11:10
Test if this happened at this commit too -

https://github.com/libretro/beetle-psx-libretro/commit/3ff904a09c41549a47104e64d398cbc41a9a5dae

**Comment by razorache** [comment] 2017-04-22 01:38
The latest build fixed this issue for me entirely

**Comment by saftle** [comment] 2017-06-11 15:22
@razorache you can close the issue, if you'd like (since the problem is solved).

**Closed** 2017-06-11 15:29 UTC
